attempt to run ngap image on startup

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -201,6 +201,19 @@ jobs:
         - show_version
         - ./build-hyrax-ngap.sh
         - docker image ls -a
+        - |
+          echo "Test that image does not crash on startup"
+          docker run --name=test_image "${OS_BUILD_VERSION_TAG}"
+          DOCKER_RESULT=$(docker ps -a | grep Exited)
+          if [ -n DOCKER_RESULT ]; then
+            echo "Error: Image $(OS_BUILD_VERSION_TAG) failed at entrypoint"
+            docker ps -a
+            echo "Log from failing test instance:"
+            docker logs test_image
+            exit 1
+          else
+            docker stop test_image
+          fi
 
     - stage: TEST_DEPLOYED_IMAGE
       name: "Test Deployed Image"
