Dropped tomcat:9 in javor of rocky:8 for OLFS vm

diff --git a/hyrax-builds/olfs/Dockerfile b/hyrax-builds/olfs/Dockerfile
--- a/hyrax-builds/olfs/Dockerfile
+++ b/hyrax-builds/olfs/Dockerfile
@@ -3,12 +3,25 @@
 ###
 
 #
-FROM tomcat:9
+FROM rockylinux:8
 MAINTAINER support@opendap.org
+USER root
 
+RUN export NOW=`date +%s`
 ARG RELEASE_DATE
-ENV RELEASE_DATE ${RELEASE_DATE:-"unknown"}
+ENV RELEASE_DATE ${RELEASE_DATE:-"${NOW}"}
 RUN echo "RELEASE_DATE: ${RELEASE_DATE}"
+
+ARG TOMCAT_VERSION
+ENV TOMCAT_VERSION ${TOMCAT_VERSION:-"9.0.64"}
+RUN echo "TOMCAT_VERSION: ${TOMCAT_VERSION}"
+ENV TOMCAT_DISTRO="apache-tomcat-${TOMCAT_VERSION}"
+COPY "${TOMCAT_DISTRO}.tar.gz" /
+RUN ls -l /apache-tomcat-*  >&2
+
+ARG HYRAX_VERSION
+ENV HYRAX_VERSION=${HYRAX_VERSION:-"snapshot"}
+RUN echo "HYRAX_VERSION: ${HYRAX_VERSION}"
 
 ARG OLFS_VERSION
 ENV OLFS_VERSION=${OLFS_VERSION:-"unknown"}
@@ -19,25 +32,15 @@ ENV OLFS_DISTRO=${OLFS_DISTRO:-"olfs-${OLFS_VERSION}-webapp"}
 RUN echo "OLFS_DISTRO: ${OLFS_DISTRO}"
 COPY ${OLFS_DISTRO}.tgz /${OLFS_DISTRO}.tgz
 
+ARG ROBOTS_DISTRO
+ENV ROBOTS_DISTRO=${ROBOTS_DISTRO:-"robots-olfs-${OLFS_VERSION}-webapp"}
+RUN echo "ROBOTS_DISTRO: ${ROBOTS_DISTRO}"
+COPY ${ROBOTS_DISTRO}.tgz /${ROBOTS_DISTRO}.tgz
+
 LABEL vendor="OPeNDAP"
 LABEL org.opendap.olfs.version=${OLFS_VERSION}
 LABEL org.opendap.olfs.release-date=RELEASE_DATE
 LABEL org.opendap.hyrax.version.is-production="false"
-
-USER root
-
-# Hack to fix broken apt-get update
-RUN set -e && apt list --installed
-
-# Update OS and install ps (and other filesystem utils)
-#RUN set -e && apt-get -y update
-
-#RUN set -e && sed -i 's/# \(.*multiverse$\)/\1/g' /etc/apt/sources.list
-#RUN set -e && rm -fr /var/lib/apt/lists
-#RUN set -e && mkdir -pv /var/lib/apt/lists/partial
-#RUN set -e && apt-get -oDebug::pkgAcquire::Worker=1 update
-#RUN set -e && apt-get -y upgrade
-#RUN set -e && apt-get -y install unzip
 
 #
 # The --build-arg USE_NCWMS can be set to "true" in order to 
@@ -57,49 +60,100 @@ ENV NCWMS_BASE ${NCWMS_BASE:-"https://localhost:8080"}
 RUN set -e && \
     if [ $USE_NCWMS = "true" ];then echo "NCWMS_BASE: {$NCWMS_BASE}"; fi
 
-###
-# Grab and unzip the OLFS
-###
-# Tomcat environment?
-ENV PATH $CATALINA_HOME/bin:$PATH
-RUN echo "CATALINA_HOME: $CATALINA_HOME"
 
-# SNAPSHOT URLs
-RUN echo "OLFS_VERSION: ${OLFS_VERSION}"
-
-###############################################################
-# Retrieve, verify, and install the OLFS web application
-# In the following, replaced unzip with jar because unzip was failing with a message
-# about the archive containing a 'loop' of some sort. The original line was:
-#     unzip -o /dev/shm/olfs-snapshot-webapp/opendap.war -d ${CATALINA_HOME}/webapps/opendap/
-# and the new line is:
-#     (cd ${CATALINA_HOME}/webapps/opendap/ && jar -xf /dev/shm/olfs-snapshot-webapp/opendap.war)
+################################################################
+# Update and install the needful.
 #
+# Installing autoconf automake git bc for the tests install. The tests
+# are installed in the container but not run until a later stage of the
+# Travis build (or at a later time). They need to be part of the container,
+# however, to be run, so install them as part of this Dockerfile.
+RUN set -e \
+    && dnf update  -y \
+    && dnf install -y curl unzip which emacs vim \
+    && dnf install -y python3 git bc \
+    && dnf install -y java-11-openjdk-devel \
+    && dnf clean all
+#
+RUN set -e \
+    && python3 -m pip install awscli
+
+
+################################################################
+# Install and Setup Tomcat
+#
+# Make tomcat user and group
+#  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
+RUN set -e && useradd -m -U -d /home/tomcat -s /bin/false tomcat
+#
+# Install the Tomcat package that should have been copied into
+# the root directory prior to this layer.
+#
+RUN set -e \
+    && tar -xvf "/${TOMCAT_DISTRO}.tar.gz" -C /home/tomcat >&2 \
+    && ln -s /home/tomcat/${TOMCAT_DISTRO} /usr/share/tomcat >&2 \
+    && rm -rvf /usr/share/tomcat/webapps/* >&2 \
+    && mkdir -p /var/log/tomcat \
+    && chown -R tomcat:tomcat /var/log/tomcat /home/tomcat
+COPY tomcat.service /etc/systemd/system/tomcat.service
+RUN set -e && systemctl enable tomcat
+#RUN firewall-cmd --add-port 8080/tcp --permanent
+#RUN firewall-cmd --reload
+
+ENV CATALINA_HOME /usr/share/tomcat
+ENV PATH $CATALINA_HOME/bin:$PATH
+RUN set -e && echo "CATALINA_HOME: ${CATALINA_HOME}" >&2
+
+# Install our modified server.xml so that the server compresses responses.
+COPY tomcat9-server.xml /
+RUN set -e \
+    && mv /tomcat9-server.xml ${CATALINA_HOME}/conf/server.xml \
+    && chown -R tomcat:tomcat ${CATALINA_HOME}/conf/server.xml
+
+RUN set -e \
+    && echo "Cleaning up Tomcat distribution files..." >&2 \
+    && rm -fv "/${TOMCAT_DISTRO}.tar.gz"
+
+
+################################################################
+# Install the OLFS web application
+#  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
 ENV ROOT=/dev/shm
-ENV DIST_WAR_FILE="${ROOT}/${OLFS_DISTRO}/opendap.war"
-RUN echo "Installing the latest olfs snapshot (${OLFS_VERSION}.tgz)."
+
+RUN echo "Installing the latest olfs distribution (${OLFS_VERSION})." >&2
 RUN set -e \
-    && tar -C ${ROOT} -xzvf /${OLFS_DISTRO}.tgz \
+    && echo "working_dir: "`pwd`  >&2 \
+    && ls -l . \
+    && tar -C ${ROOT} -xzvf ./${OLFS_DISTRO}.tgz \
     && ls -l ${ROOT} \
-    && mkdir -p $(readlink -f ${CATALINA_HOME})/webapps/opendap/
-
-RUN set -e \
-    && echo "Unpacking warfile..." \
-    && cd ${CATALINA_HOME}/webapps/opendap/ \
-    && jar -xf ${ROOT}/${OLFS_DISTRO}/opendap.war
-
-#RUN set -e \
-#    && echo "Unpacking warfile ${DIST_WAR_FILE}" \
-#    && unzip -o ${DIST_WAR_FILE} -d ${CATALINA_HOME}/webapps/opendap/
-
-RUN set -e \
+    && echo "Unpacking warfile..."  >&2 \
+    && mkdir -p $(readlink -f ${CATALINA_HOME})/webapps/opendap/ \
+    && unzip -o ${ROOT}/${OLFS_DISTRO}/opendap.war -d ${CATALINA_HOME}/webapps/opendap/ \
     && echo "Cleaning up."  >&2 \
-    && rm -rf ${ROOT}/${OLFS_DISTRO} /${OLFS_DISTRO}.tgz
+    && rm -rf ${ROOT}/${OLFS_DISTRO} ./${OLFS_DISTRO}.tgz
 
+RUN set -e \
+    && echo "Installing the latest dynamic robots.txt distribution (${OLFS_VERSION})."  >&2 \
+    && ls -l ./robots* \
+    && tar -C ${ROOT} -xzf ./${ROBOTS_DISTRO}.tgz \
+    && ls -l ${ROOT}/${ROBOTS_DISTRO} \
+    && echo "Unpacking dynamic robots.txt warfile..."  >&2 \
+    && unzip -o ${ROOT}/${ROBOTS_DISTRO}/ROOT.war -d ${CATALINA_HOME}/webapps/ROOT/ \
+    && echo "Cleaning up dynamic robots.txt snapshot..."  >&2 \
+    && rm -rf ${ROOT}/${ROBOTS_DISTRO} ${ROBOTS_DISTRO}.tgz
 
-#    && echo "Installing warfile ${DIST_WAR_FILE}"  >&2 \
-#    && cp "${WAR_FILE}" ${CATALINA_HOME}/webapps \
-#    && rm -rf ${ROOT}/${OLFS_DISTRO} /${OLFS_DISTRO}.tgz
+# Fix ownership and access permissions
+RUN set -e \
+    && mkdir -p ${CATALINA_HOME}/webapps/opendap/WEB-INF/conf/logs \
+    && chown -R tomcat:tomcat ${CATALINA_HOME}/webapps/opendap/WEB-INF/conf/logs \
+    && chmod 700 ${CATALINA_HOME}/webapps/opendap/WEB-INF/conf/logs
+
+################################################################
+# Clean up the distribution binaries.
+#
+RUN rm -vf  /olfs*.tgz /robots*.tgz /apache*
+#
+################################################################
 
 
 
