WIP

diff --git a/el9-builds/build-el9 b/el9-builds/build-el9
--- a/el9-builds/build-el9
+++ b/el9-builds/build-el9
@@ -554,25 +554,36 @@ function s3_pull(){
     local prolog="s3_pull() -"
     loggy "$prolog BEGIN"
 
-    local bucket_name="${1}"
+    local bucket_name="$1"
     loggy "$prolog bucket_name: $bucket_name"
 
-    local object_name="${2}"
+    local object_name="$2"
     loggy "$prolog object_name: $object_name"
 
-    local target_dir="${3}"
+    local target_dir="$3"
     loggy "$prolog  target_dir: $target_dir"
 
-    local s3_url="s3://${bucket_name}/${object_name}"
+    local s3_url="s3://$bucket_name/$object_name"
     loggy "$prolog      s3_url: $s3_url"
     loggy "$prolog   aws s3 ls: $(aws s3 ls "$s3_url")"
 
-    local target_file="${target_dir}/${object_name}"
+    local target_file="$target_dir/$object_name"
     loggy "$prolog target_file: $target_file"
 
     local be_quiet
-    if test -n "${aws_quiet}"; then be_quiet="--quiet"; fi
+    if test -n "$aws_quiet"; then be_quiet="--quiet"; fi
     loggy "$prolog    be_quiet: '$be_quiet'"
+
+    loggy "$prolog    Checking for the existence of '$object_name' in '$bucket_name' "
+#    aws s3api head-object --bucket "$bucket_name" --key path/to/your/object.txt
+    aws s3 ls "$s3_url"
+    status=$?
+    if test $status -ne 0
+    then
+        loggy "ERROR! Failed to locate '$object_name' in '$bucket_name'. Bad things are happening."
+        return $status
+    fi
+
 
     loggy "$prolog  Retrieving: $s3_url"
     aws s3 cp $be_quiet "$s3_url" "$target_file"
