Update el-9 shared and besd build

diff --git a/el9-builds/besd/Dockerfile b/el9-builds/besd/Dockerfile
--- a/el9-builds/besd/Dockerfile
+++ b/el9-builds/besd/Dockerfile
@@ -14,7 +14,18 @@
 #
 # Set one or more individual labels
 #
-FROM rockylinux:9
+ARG BES_CORE_IMAGE_TAG
+FROM ${BES_CORE_IMAGE_TAG:-"rockylinux:8"}
+
+ARG BES_CORE_IMAGE_TAG
+RUN if [ -z "$BES_CORE_IMAGE_TAG" ]; then \
+        echo "Error: Non-empty BES_CORE_IMAGE_TAG must be specified. Exiting."; \
+        exit 1; \
+    fi
+
+# User defined and created in the `bes_core` image
+ENV BES_USER ${USER:-"bes_user"}
+
 ENV HR="###############################################################################################################"
 ENV HR2="-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --"
 ENV TARGET_OS="el9"
@@ -37,22 +48,23 @@ RUN echo "RELEASE_DATE: $RELEASE_DATE"
 
 ARG LIBDAP_VERSION
 ENV LIBDAP_VERSION=${LIBDAP_VERSION:-"snapshot-$TARGET_OS"}
-RUN echo "LIBDAP_VERSION: $LIBDAP_VERSION"
-
-ARG LIBDAP_RPM
-ENV LIBDAP_RPM=${LIBDAP_RPM:-"libdap-$LIBDAP_VERSION.$TARGET_OS.x86_64.rpm"}
-RUN echo "LIBDAP_RPM: $LIBDAP_RPM"
-COPY "$LIBDAP_RPM" "/$LIBDAP_RPM"
+RUN LIBDAP_VERSION_FOUND=$(cat libdap_VERSION); \
+    if [ "${LIBDAP_VERSION_FOUND}" == "${LIBDAP_VERSION:-missing}" ]; then \
+        echo "LIBDAP_VERSION: ${LIBDAP_VERSION}"; \
+    else \
+        echo "Error: Expected LIBDAP_VERSION `${LIBDAP_VERSION}`, found version `${LIBDAP_VERSION_FOUND}`. Exiting."; \
+        exit 1; \
+    fi
 
 ARG BES_VERSION
 ENV BES_VERSION=${BES_VERSION:-"snapshot-$TARGET_OS"}
-RUN echo "BES_VERSION: $BES_VERSION"
-
-ARG BES_RPM
-ENV BES_RPM=${BES_RPM:-"bes-$BES_VERSION.static.$TARGET_OS.x86_64.rpm"}
-RUN echo "BES_RPM: $BES_RPM"
-COPY "$BES_RPM" "/$BES_RPM"
-
+RUN BES_VERSION_FOUND=$(cat bes_VERSION); \
+    if [ "${BES_VERSION_FOUND}" == "${BES_VERSION:-missing}" ]; then \
+        echo "BES_VERSION: ${BES_VERSION}"; \
+    else \
+        echo "Error: Expected BES_VERSION \"${BES_VERSION}\", found version \"${BES_VERSION_FOUND}\". Exiting."; \
+        exit 1; \
+    fi
 
 LABEL vendor="OPeNDAP Incorporated"
 LABEL org.opendap.besdaemon.version="$BES_VERSION"
@@ -61,6 +73,7 @@ LABEL org.opendap.hyrax.version.is-production="false"
 LABEL org.opencontainers.image.authors="support@opendap.org"
 
 USER root
+WORKDIR /
 
 ######################################################################
 # Update the OS and create a handy executable shell scipt to simplify
@@ -71,38 +84,45 @@ RUN set -e \
     && dnf install -y $dnf_runtime_packages \
     && echo "#!/bin/bash" > /install-dev-tools \
     && echo "dnf install -y $dnf_developer_tools_packages" > /install-dev-tools \
-    && chmod 755 /install-dev-tools
+    && chmod 755 /install-dev-tools \
+    && dnf clean all
 
-################################################################
-# Install the libdap rpm
-#  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
-RUN set -e \
-    && echo "$HR" >&2 \
-    && echo "# Installing the libdap rpm: $LIBDAP_RPM" >&2 \
-    && ls -l ./libdap* \
-    && dnf -y install ./libdap-*.rpm \
-    && echo "# The 'dnf install' command exited with status: $?" >&2 \
-    && rm -f "./$LIBDAP_RPM" \
-    && dnf clean all \
-    && echo "# libdap4 is installed." >&2 \
-    && echo "$HR" >&2
+######################################################################
 
-################################################################
-# Install the the BES
-# besd, besdaemon, beslistener, besctl, besstandalone, bescmdline
-#  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
-RUN set -e \
-    && echo "$HR" >&2 \
-    && echo "# Installing the BES rpm: $BES_RPM" >&2 \
-    && ls -l ./bes* \
-    && dnf -y install ./bes-*.rpm \
-    && echo "# The 'dnf install' command exited with status: $?" >&2 \
-    && rm -f "./$BES_RPM" \
-    && dnf clean all \
-    && echo "# besdaemon is here: $(which besdaemon)" >&2 \
-    && echo "#      besdaemon -v: '$(besdaemon -v)'" >&2 \
-    && echo "$HR" >&2
+# Set up BES
+#
+# BES is already installed on the base image, but
+# we need to do some additional configuration (to match what was
+# previously handled by bes RPM installation)
 
+# Add besd service to start at boot
+RUN cp ${PREFIX}/etc/rc.d/init.d/besd /etc/rc.d/init.d/besd \
+    && chkconfig --add besd \
+    && ldconfig \
+    && chkconfig --list | grep besd \
+    && echo "whoami: "`whoami` \
+    && echo "besdaemon is here: "`which besdaemon`
+
+# Adapted from bes/spec.all_static.in in RPM creation.
+# The four *.pem substitutions may be unnecessary, as those *.pem files may be
+# vestigial substitutions for a build process past.
+RUN sed -i.dist \
+    -e 's:=.*/bes.log:=/var/log/bes/bes.log:' \
+    -e 's:=.*/lib/bes:='"$PREFIX"'/lib/bes:' \
+    -e 's:=.*/share/bes:='"$PREFIX"'/share/bes:' \
+    -e 's:=.*/share/hyrax:='"$PREFIX"'/share/hyrax:' \
+    -e 's:=/full/path/to/serverside/certificate/file.pem:=/etc/pki/bes/cacerts/file.pem:' \
+    -e 's:=/full/path/to/serverside/key/file.pem:=/etc/pki/bes/public/file.pem:' \
+    -e 's:=/full/path/to/clientside/certificate/file.pem:=/etc/pki/bes/cacerts/file.pem:' \
+    -e 's:=/full/path/to/clientside/key/file.pem:=/etc/pki/bes/public/file.pem:' \
+    -e 's:=user_name:='"$BES_USER"':' \
+    -e 's:=group_name:='"$BES_USER"':' \
+    $PREFIX/etc/bes/bes.conf \
+    && mkdir -p "/var/log/bes/" \
+    && touch "/var/log/bes/bes.log" \
+    && sudo chown -R $BES_USER:$BES_USER "/var/log/bes/"
+
+RUN echo "besdaemon is here: "`which besdaemon`
 
 COPY entrypoint.sh /entrypoint.sh
 RUN  chmod +x /entrypoint.sh
@@ -110,11 +130,6 @@ ENTRYPOINT ["/entrypoint.sh"]
 
 EXPOSE 10022
 EXPOSE 11002
-
-# can't use USER with entrypoint that needs root
-# use gosu or, as done, enable bes user write so the entrypoint doe snot need root
-RUN  chown -R bes /etc/bes
-USER root
 
 CMD ["-"]
 
