wip copy rpm install behavior, permissions not yet correct

diff --git a/builds/hyrax/Dockerfile b/builds/hyrax/Dockerfile
--- a/builds/hyrax/Dockerfile
+++ b/builds/hyrax/Dockerfile
@@ -13,8 +13,12 @@
 # it for debugging stuff.
 #
 # Set one or more individual labels
+
+# Add a default base image to keep docker from complaining,
+# which is fine because if this ISN'T based on a given image tag,
+# everything downstream will fail due to lack of bes, libdap, etc.
 ARG BES_IMAGE_TAG
-FROM ${BES_IMAGE_TAG}
+FROM ${BES_IMAGE_TAG:-"rockylinux:8"}
 
 ENV NOW="$(`date +%s`)"
 ARG RELEASE_DATE
@@ -25,8 +29,8 @@ ARG TOMCAT_VERSION
 ENV TOMCAT_VERSION=${TOMCAT_VERSION:-"9.0.64"}
 RUN echo "TOMCAT_VERSION: ${TOMCAT_VERSION}"
 ENV TOMCAT_DISTRO="apache-tomcat-${TOMCAT_VERSION}"
-# COPY "${TOMCAT_DISTRO}.tar.gz" /
-# RUN ls -l /apache-tomcat-*  >&2
+COPY "${TOMCAT_DISTRO}.tar.gz" /
+RUN ls -l /apache-tomcat-*  >&2
 
 ARG HYRAX_VERSION
 ENV HYRAX_VERSION=${HYRAX_VERSION:-"snapshot"}
@@ -47,15 +51,15 @@ ARG OLFS_VERSION
 ENV OLFS_VERSION=${OLFS_VERSION:-"snapshot"}
 RUN echo "OLFS_VERSION: ${OLFS_VERSION}"
 
-# ARG OLFS_DISTRO
-# ENV OLFS_DISTRO=${OLFS_DISTRO:-"olfs-${OLFS_VERSION}-webapp"}
-# RUN echo "OLFS_DISTRO: ${OLFS_DISTRO}"
-# COPY ${OLFS_DISTRO}.tgz /${OLFS_DISTRO}.tgz
+ARG OLFS_DISTRO
+ENV OLFS_DISTRO=${OLFS_DISTRO:-"olfs-${OLFS_VERSION}-webapp"}
+RUN echo "OLFS_DISTRO: ${OLFS_DISTRO}"
+COPY ${OLFS_DISTRO}.tgz /${OLFS_DISTRO}.tgz
 
-# ARG ROBOTS_DISTRO
-# ENV ROBOTS_DISTRO=${ROBOTS_DISTRO:-"robots-olfs-${OLFS_VERSION}-webapp"}
-# RUN echo "ROBOTS_DISTRO: ${ROBOTS_DISTRO}"
-# COPY ${ROBOTS_DISTRO}.tgz /${ROBOTS_DISTRO}.tgz
+ARG ROBOTS_DISTRO
+ENV ROBOTS_DISTRO=${ROBOTS_DISTRO:-"robots-olfs-${OLFS_VERSION}-webapp"}
+RUN echo "ROBOTS_DISTRO: ${ROBOTS_DISTRO}"
+COPY ${ROBOTS_DISTRO}.tgz /${ROBOTS_DISTRO}.tgz
 
 ARG DEPLOYMENT_CONTEXT
 ENV DEPLOYMENT_CONTEXT=${DEPLOYMENT_CONTEXT:-"opendap"}
@@ -103,7 +107,7 @@ RUN if [ $DEVELOPER_MODE = "true" ];then echo "DEVELOPER_MODE: ENABLED"; else ec
 # are installed in the container but not run until a later stage of the
 # Travis build (or at a later time). They need to be part of the container,
 # however, to be run, so install them as part of this Dockerfile.
-RUN set -e && dnf update  -y
+# RUN set -e && dnf update  -y
 RUN set -e && dnf install -y python3.11 \
     && python3 --version
 
@@ -128,185 +132,206 @@ RUN set -e && which diff
 
 RUN echo "besdaemon is here: "`which besdaemon`
 
-# Instead of rpm pre:
+# Add bes group and user (previously constructed via rpm installation)
 RUN getent group bes >/dev/null || groupadd -r bes
 RUN getent passwd bes >/dev/null || \
     useradd -r -g bes -d /var/log/bes -s /sbin/nologin -c "BES daemon" bes
 
-# Instead of rpm post: #TODO-maybe: cd into bes dir first??
-RUN chkconfig --add besd
+# Instead of rpm post:
+RUN cp ./usr/local/etc/rc.d/init.d/besd /etc/rc.d/init.d/besd
+RUN chkconfig --add besd \
+    && ldconfig
 
-# ################################################################
-# # Install and Setup Tomcat
-# #
-# # Make tomcat user and group
-# #  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
-# RUN set -e && useradd -m -U -d /home/tomcat -s /bin/false tomcat
-# #
-# # Install the Tomcat package that should have been copied into
-# # the root directory prior to this layer.
-# #
-# RUN set -e \
-#     && tar -xvf "/${TOMCAT_DISTRO}.tar.gz" -C /home/tomcat >&2 \
-#     && ln -s /home/tomcat/${TOMCAT_DISTRO} /usr/share/tomcat >&2 \
-#     && ln -s /home/tomcat/${TOMCAT_DISTRO} /tomcat >&2 \
-#     && rm -rvf /usr/share/tomcat/webapps/* >&2 \
-#     && mkdir -p /var/log/tomcat \
-#     && chown -R tomcat:tomcat /var/log/tomcat /home/tomcat
-# COPY tomcat.service /etc/systemd/system/tomcat.service
-# RUN set -e && systemctl enable tomcat
-# #RUN firewall-cmd --add-port 8080/tcp --permanent
-# #RUN firewall-cmd --reload
+# More rpm-adapting hijinks
+# Adapted from bes/spec.all_static.in
+# Default macros: https://docs.fedoraproject.org/en-US/packaging-guidelines/RPMMacros/
+RUN sed -i.dist -e 's:=/tmp:=/var/cache/bes:' \
+    -e 's:=.*/bes.log:=/var/log/bes/bes.log:' \
+    -e 's:=.*/lib/bes:=/usr/lib/bes:' \
+    -e 's:=.*/share/bes:=/usr/share/bes:' \
+    -e 's:=.*/share/hyrax:=/usr/share/hyrax:' \
+    -e 's:=/full/path/to/serverside/certificate/file.pem:=/etc/pki/bes/cacerts/file.pem:' \
+    -e 's:=/full/path/to/serverside/key/file.pem:=/etc/pki/bes/public/file.pem:' \
+    -e 's:=/full/path/to/clientside/certificate/file.pem:=/etc/pki/bes/cacerts/file.pem:' \
+    -e 's:=/full/path/to/clientside/key/file.pem:=/etc/pki/bes/public/file.pem:' \
+    -e 's:=user_name:=bes:' \
+    -e 's:=group_name:=bes:' \
+    /usr/local/etc/bes/bes.conf
 
-# ENV CATALINA_HOME=/usr/share/tomcat
-# ENV PATH=$CATALINA_HOME/bin:$PATH
-# RUN set -e && echo "CATALINA_HOME: ${CATALINA_HOME}" >&2
+RUN chown -R bes /usr/local/etc/bes \
+    /usr/local/share/bes \
+    /usr/local/include/bes \
+    /usr/local/lib/bes \
+    /usr/local/var/run/bes
 
-# # Install our modified server.xml so that the server compresses responses.
-# COPY tomcat9-server.xml /
-# RUN set -e \
-#     && mv /tomcat9-server.xml ${CATALINA_HOME}/conf/server.xml \
-#     && chown -R tomcat:tomcat ${CATALINA_HOME}/conf/server.xml
+################################################################
+# Install and Setup Tomcat
+#
+# Make tomcat user and group
+#  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
+RUN set -e && useradd -m -U -d /home/tomcat -s /bin/false tomcat
+#
+# Install the Tomcat package that should have been copied into
+# the root directory prior to this layer.
+#
+RUN set -e \
+    && tar -xvf "/${TOMCAT_DISTRO}.tar.gz" -C /home/tomcat >&2 \
+    && ln -s /home/tomcat/${TOMCAT_DISTRO} /usr/share/tomcat >&2 \
+    && ln -s /home/tomcat/${TOMCAT_DISTRO} /tomcat >&2 \
+    && rm -rvf /usr/share/tomcat/webapps/* >&2 \
+    && mkdir -p /var/log/tomcat \
+    && chown -R tomcat:tomcat /var/log/tomcat /home/tomcat
+COPY tomcat.service /etc/systemd/system/tomcat.service
+RUN set -e && systemctl enable tomcat
+#RUN firewall-cmd --add-port 8080/tcp --permanent
+#RUN firewall-cmd --reload
 
-# RUN set -e \
-#     && echo "Cleaning up Tomcat distribution files..." >&2 \
-#     && rm -fv "/${TOMCAT_DISTRO}.tar.gz"
+ENV CATALINA_HOME=/usr/share/tomcat
+ENV PATH=$CATALINA_HOME/bin:$PATH
+RUN set -e && echo "CATALINA_HOME: ${CATALINA_HOME}" >&2
 
-# ################################################################
-# # Install the OLFS web application
-# #  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
-# ENV ROOT=/dev/shm
+# Install our modified server.xml so that the server compresses responses.
+COPY tomcat9-server.xml /
+RUN set -e \
+    && mv /tomcat9-server.xml ${CATALINA_HOME}/conf/server.xml \
+    && chown -R tomcat:tomcat ${CATALINA_HOME}/conf/server.xml
 
-# RUN echo "Installing the latest olfs distribution (${OLFS_VERSION})." >&2
-# RUN set -e \
-#     && echo "working_dir: "`pwd`  >&2 \
-#     && ls -l . \
-#     && tar -C ${ROOT} -xzvf ./${OLFS_DISTRO}.tgz \
-#     && ls -l ${ROOT} \
-#     && echo "Unpacking warfile..."  >&2 \
-#     && mkdir -p $(readlink -f ${CATALINA_HOME})/webapps/${DEPLOYMENT_CONTEXT}/ \
-#     && unzip -o ${ROOT}/${OLFS_DISTRO}/opendap.war -d ${CATALINA_HOME}/webapps/${DEPLOYMENT_CONTEXT}/ \
-#     && echo "Cleaning up."  >&2 \
-#     && rm -rf ${ROOT}/${OLFS_DISTRO} ./${OLFS_DISTRO}.tgz
+RUN set -e \
+    && echo "Cleaning up Tomcat distribution files..." >&2 \
+    && rm -fv "/${TOMCAT_DISTRO}.tar.gz"
 
-# RUN set -e \
-#     && echo "Installing the latest dynamic robots.txt distribution (${OLFS_VERSION})."  >&2 \
-#     && ls -l ./robots* \
-#     && tar -C ${ROOT} -xzf ./${ROBOTS_DISTRO}.tgz \
-#     && ls -l ${ROOT}/${ROBOTS_DISTRO} \
-#     && echo "Unpacking dynamic robots.txt warfile..."  >&2 \
-#     && unzip -o ${ROOT}/${ROBOTS_DISTRO}/ROOT.war -d ${CATALINA_HOME}/webapps/ROOT/ \
-#     && echo "Cleaning up dynamic robots.txt snapshot..."  >&2 \
-#     && rm -rf ${ROOT}/${ROBOTS_DISTRO} ${ROBOTS_DISTRO}.tgz
+################################################################
+# Install the OLFS web application
+#  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
+ENV ROOT=/dev/shm
 
-# # Fix ownership and access permissions
-# RUN set -e \
-#     && mkdir -p ${CATALINA_HOME}/webapps/${DEPLOYMENT_CONTEXT}/WEB-INF/conf/logs \
-#     && chown -R tomcat:tomcat ${CATALINA_HOME}/webapps/${DEPLOYMENT_CONTEXT}/WEB-INF/conf/logs \
-#     && chmod 700 ${CATALINA_HOME}/webapps/${DEPLOYMENT_CONTEXT}/WEB-INF/conf/logs
+RUN echo "Installing the latest olfs distribution (${OLFS_VERSION})." >&2
+RUN set -e \
+    && echo "working_dir: "`pwd`  >&2 \
+    && ls -l . \
+    && tar -C ${ROOT} -xzvf ./${OLFS_DISTRO}.tgz \
+    && ls -l ${ROOT} \
+    && echo "Unpacking warfile..."  >&2 \
+    && mkdir -p $(readlink -f ${CATALINA_HOME})/webapps/${DEPLOYMENT_CONTEXT}/ \
+    && unzip -o ${ROOT}/${OLFS_DISTRO}/opendap.war -d ${CATALINA_HOME}/webapps/${DEPLOYMENT_CONTEXT}/ \
+    && echo "Cleaning up."  >&2 \
+    && rm -rf ${ROOT}/${OLFS_DISTRO} ./${OLFS_DISTRO}.tgz
 
-# ################################################################
-# # Clean up the Hyrax distribution binaries.
-# #
-# RUN rm -vf /olfs*.tgz /robots*.tgz /apache*
-# #
-# ################################################################
+RUN set -e \
+    && echo "Installing the latest dynamic robots.txt distribution (${OLFS_VERSION})."  >&2 \
+    && ls -l ./robots* \
+    && tar -C ${ROOT} -xzf ./${ROBOTS_DISTRO}.tgz \
+    && ls -l ${ROOT}/${ROBOTS_DISTRO} \
+    && echo "Unpacking dynamic robots.txt warfile..."  >&2 \
+    && unzip -o ${ROOT}/${ROBOTS_DISTRO}/ROOT.war -d ${CATALINA_HOME}/webapps/ROOT/ \
+    && echo "Cleaning up dynamic robots.txt snapshot..."  >&2 \
+    && rm -rf ${ROOT}/${ROBOTS_DISTRO} ${ROBOTS_DISTRO}.tgz
 
-# ################################################################
-# # retrieve and install the ncWMS web application
-# #  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
+# Fix ownership and access permissions
+RUN set -e \
+    && mkdir -p ${CATALINA_HOME}/webapps/${DEPLOYMENT_CONTEXT}/WEB-INF/conf/logs \
+    && chown -R tomcat:tomcat ${CATALINA_HOME}/webapps/${DEPLOYMENT_CONTEXT}/WEB-INF/conf/logs \
+    && chmod 700 ${CATALINA_HOME}/webapps/${DEPLOYMENT_CONTEXT}/WEB-INF/conf/logs
 
-# ARG NCWMS_VERSION
-# ENV NCWMS_VERSION=${NCWMS_VERSION:-"2.5.2"}
-# RUN echo "NCWMS_VERSION: ${NCWMS_VERSION}"
-# ENV NCWMS_WAR_URL="https://github.com/Reading-eScience-Centre/ncwms/releases/download/ncwms-${NCWMS_VERSION}/ncWMS2.war"
-# RUN echo "NCWMS_WAR_URL: ${NCWMS_WAR_URL}"
+################################################################
+# Clean up the Hyrax distribution binaries.
+#
+RUN rm -vf /olfs*.tgz /robots*.tgz /apache*
+#
+################################################################
 
-# RUN if [ $USE_NCWMS = "true" ]; then \
-#         echo "Installing ncWMS..."; \
-#         curl -sfSL ${NCWMS_WAR_URL} -o /dev/shm/ncWMS.war; \
-#         unzip -o /dev/shm/ncWMS.war -d ${CATALINA_HOME}/webapps/ncWMS2/; \
-#         rm -rf /dev/shm/*; \
-#     else \
-#         echo "ncWMS will NOT be installed."; \
-#     fi
+################################################################
+# retrieve and install the ncWMS web application
+#  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
 
-# # set a default ncWMS admin if DEVELOPER_MODE is enabled.
-# RUN if [ ${DEVELOPER_MODE} = "true" ] && [ $USE_NCWMS = "true" ]; then \
-#         echo "DEVELOPER MODE: Adding ncWMS admin credentials"; \
-#         sed -i 'sX</tomcat-users>X<role rolename="ncWMS-admin"/> <user username="admin" password="admin" roles="ncWMS-admin"/> </tomcat-users>X' ${CATALINA_HOME}/conf/tomcat-users.xml; \
-#     else \
-#         echo "No ncWMS admin credentials installed."; \
-#     fi
+ARG NCWMS_VERSION
+ENV NCWMS_VERSION=${NCWMS_VERSION:-"2.5.2"}
+RUN echo "NCWMS_VERSION: ${NCWMS_VERSION}"
+ENV NCWMS_WAR_URL="https://github.com/Reading-eScience-Centre/ncwms/releases/download/ncwms-${NCWMS_VERSION}/ncWMS2.war"
+RUN echo "NCWMS_WAR_URL: ${NCWMS_WAR_URL}"
+
+RUN if [ $USE_NCWMS = "true" ]; then \
+        echo "Installing ncWMS..."; \
+        curl -sfSL ${NCWMS_WAR_URL} -o /dev/shm/ncWMS.war; \
+        unzip -o /dev/shm/ncWMS.war -d ${CATALINA_HOME}/webapps/ncWMS2/; \
+        rm -rf /dev/shm/*; \
+    else \
+        echo "ncWMS will NOT be installed."; \
+    fi
+
+# set a default ncWMS admin if DEVELOPER_MODE is enabled.
+RUN if [ ${DEVELOPER_MODE} = "true" ] && [ $USE_NCWMS = "true" ]; then \
+        echo "DEVELOPER MODE: Adding ncWMS admin credentials"; \
+        sed -i 'sX</tomcat-users>X<role rolename="ncWMS-admin"/> <user username="admin" password="admin" roles="ncWMS-admin"/> </tomcat-users>X' ${CATALINA_HOME}/conf/tomcat-users.xml; \
+    else \
+        echo "No ncWMS admin credentials installed."; \
+    fi
     
-# #
-# # make ncWMS work without further configuration 
-# # We will need to adjust this target if we
-# # decide to run as a different (not root) user.
-# COPY ncWMS_config.xml /root/.ncWMS2/config.xml
-# RUN  chmod +r /root/.ncWMS2/config.xml
+#
+# make ncWMS work without further configuration 
+# We will need to adjust this target if we
+# decide to run as a different (not root) user.
+COPY ncWMS_config.xml /root/.ncWMS2/config.xml
+RUN  chmod +r /root/.ncWMS2/config.xml
 
-# COPY olfs_viewers.xml /tmp/olfs_viewers.xml
-# RUN if [ $USE_NCWMS = "true" ]; then \
-#         # If we're installing ncWMS then we copy 
-#         # to the server a viewers.xml which has
-#         # been templated so that the ncWMS host can be installed 
-#         # at startup.
-#         mv /tmp/olfs_viewers.xml ${CATALINA_HOME}/webapps/${DEPLOYMENT_CONTEXT}/WEB-INF/conf/viewers.xml; \
-#     else \
-#         echo "Skipping OLFS/ncWMS confguration installation."; \
-#     fi
+COPY olfs_viewers.xml /tmp/olfs_viewers.xml
+RUN if [ $USE_NCWMS = "true" ]; then \
+        # If we're installing ncWMS then we copy 
+        # to the server a viewers.xml which has
+        # been templated so that the ncWMS host can be installed 
+        # at startup.
+        mv /tmp/olfs_viewers.xml ${CATALINA_HOME}/webapps/${DEPLOYMENT_CONTEXT}/WEB-INF/conf/viewers.xml; \
+    else \
+        echo "Skipping OLFS/ncWMS confguration installation."; \
+    fi
 
-# ################################################################
-# #
-# # Retrieve, verify, and install the hyrax_regression_tests
-# # project
-# #
-# #  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
-# ENV TEST_INSTALL_DIR="/hyrax_regression_tests"
-# RUN set -e \
-#     && echo "Retrieving, and building hyrax regression tests." \
-#     && echo "h_r_t will be in: ${TEST_INSTALL_DIR}" \
-#     && mkdir -p ${TEST_INSTALL_DIR} \
-#     && git clone -v https://github.com/opendap/hyrax_regression_tests ${TEST_INSTALL_DIR} \
-#     && cd ${TEST_INSTALL_DIR} \
-#     && autoreconf -vif \
-#     && ./configure
+################################################################
+#
+# Retrieve, verify, and install the hyrax_regression_tests
+# project
+#
+#  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
+ENV TEST_INSTALL_DIR="/hyrax_regression_tests"
+RUN set -e \
+    && echo "Retrieving, and building hyrax regression tests." \
+    && echo "h_r_t will be in: ${TEST_INSTALL_DIR}" \
+    && mkdir -p ${TEST_INSTALL_DIR} \
+    && git clone -v https://github.com/opendap/hyrax_regression_tests ${TEST_INSTALL_DIR} \
+    && cd ${TEST_INSTALL_DIR} \
+    && autoreconf -vif \
+    && ./configure
 
-# # In order to get the executable "testsuite" to build we have to run
-# # "make check" But that will fail at build time so the "make check" call
-# # ends up pretty tortured to avoid a build error.
-# RUN set -e \
-#     && cd ${TEST_INSTALL_DIR} \
-#     && make testsuite > mk.log 2>&1 \
-#     && echo "SUCCESS: hyrax_regression_tests ready!"
-# ################################################################
+# In order to get the executable "testsuite" to build we have to run
+# "make check" But that will fail at build time so the "make check" call
+# ends up pretty tortured to avoid a build error.
+RUN set -e \
+    && cd ${TEST_INSTALL_DIR} \
+    && make testsuite > mk.log 2>&1 \
+    && echo "SUCCESS: hyrax_regression_tests ready!"
+################################################################
 
-# RUN ls -l /usr/libexec/
+RUN ls -l /usr/libexec/
 
-# ################################################################
-# # TEMPORARY
-# # Grab the cleanup files script for managing orphaned files
-# # from fileout_netcdf
-# COPY cleanup_files.sh /
-# RUN chmod +x /cleanup_files.sh
-# # TEMPORARY
-# ################################################################
+################################################################
+# TEMPORARY
+# Grab the cleanup files script for managing orphaned files
+# from fileout_netcdf
+COPY cleanup_files.sh /
+RUN chmod +x /cleanup_files.sh
+# TEMPORARY
+################################################################
 
 
-# COPY entrypoint.sh /
-# RUN chmod +x /entrypoint.sh
-# # ENTRYPOINT [ "/entrypoint.sh" ]
+COPY entrypoint.sh /
+RUN chmod +x /entrypoint.sh
+ENTRYPOINT [ "/entrypoint.sh" ]
 
-# EXPOSE 8009
-# EXPOSE 8080
-# EXPOSE 8443
-# EXPOSE 10022
-# EXPOSE 11002
+EXPOSE 8009
+EXPOSE 8080
+EXPOSE 8443
+EXPOSE 10022
+EXPOSE 11002
 
-# can't use USER with entrypoint that needs root
-# use gosu or, as done, enable bes user write so the entrypoint does not need root
-RUN chown -R bes /etc/bes
 USER root
 
 CMD ["-"]
