comment out to fail slower

diff --git a/el8-builds/hyrax/Dockerfile b/el8-builds/hyrax/Dockerfile
--- a/el8-builds/hyrax/Dockerfile
+++ b/el8-builds/hyrax/Dockerfile
@@ -16,11 +16,11 @@
 ARG BES_CORE_IMAGE_TAG
 FROM ${BES_CORE_IMAGE_TAG:-"rockylinux:8"}
 
-ARG BES_CORE_IMAGE_TAG
-RUN if [ -z "$BES_CORE_IMAGE_TAG" ]; then \
-        echo "Error: Non-empty BES_CORE_IMAGE_TAG must be specified. Exiting."; \
-        exit 1; \
-    fi
+# ARG BES_CORE_IMAGE_TAG
+# RUN if [ -z "$BES_CORE_IMAGE_TAG" ]; then \
+#         echo "Error: Non-empty BES_CORE_IMAGE_TAG must be specified. Exiting."; \
+#         exit 1; \
+#     fi
 
 ENV ARCH="x86_64"
 ENV java_version="java-11-openjdk"
