Single image Hyrax-1.13.4 now with signature verification, v0

diff --git a/hyrax/Dockerfile b/hyrax/Dockerfile
--- a/hyrax/Dockerfile
+++ b/hyrax/Dockerfile
@@ -1,53 +1,101 @@
 ###
 # Dockerfile for Hyrax BES
-###
+#
+#
+# Some shell state reference:
+# set -f # "set -o noglob"  Disable file name generation using metacharacters (globbing).
+# set -v # "set -o verbose" Prints shell input lines as they are read.
+# set -x # "set -o xtrace"  Print command traces before executing command.
+# set -e #  Exit on error.
+#
+# In general use "set -e" when running commands that matter and don;t use
+# it for debug stuff.
 
 FROM centos:7
-#FROM unidata/tomcat-docker:8
 
 MAINTAINER support@opendap.org
 
 USER root
 
-# Recommended maintenance
+# Update and install the needful.
 RUN \
     yum -y install which unzip tomcat && \
     yum -y update && \
     yum clean all 
 
-
+# Tomcat environment (Tomcat installed above by via yum)
 ENV CATALINA_HOME /usr/share/tomcat
 ENV PATH $CATALINA_HOME/bin:$PATH
 RUN echo "CATALINA_HOME: $CATALINA_HOME"
 
-# Install the BES from RPM
+# Installs the OPeNDAP security public key.
+# TODO: We should get this from a well known key-server instead.
+RUN echo "Adding OPeNDAP Public Security Key"
+ENV OPENDAP_PUBLIC_KEY_FILE="security_at_opendap.org.pub.asc"
+ENV OPENDAP_PUBLIC_KEY_URL="https://www.opendap.org/${OPENDAP_PUBLIC_KEY_FILE}"
+RUN set -e \
+    && curl -s $OPENDAP_PUBLIC_KEY_URL > $OPENDAP_PUBLIC_KEY_FILE \
+    && gpg --import $OPENDAP_PUBLIC_KEY_FILE
+
+# HYRAX VERSION INFO
 ENV HYRAX_VERSION=1.13.4 
+ENV LIBDAP_VERSION=3.19.0-1
+ENV BES_VERSION=3.18.0-1
 ENV OLFS_VERSION=1.16.3
 
-ENV LIBDAP_RPM="https://www.opendap.org/pub/binary/hyrax-1.13.4/centos-7.x/libdap-3.19.0-1.el7.centos.x86_64.rpm"
-ENV BES_RPM="https://www.opendap.org/pub/binary/hyrax-1.13.4/centos-7.x/bes-3.18.0-1.static.el7.centos.x86_64.rpm"
+# RELEASE URLs
+ENV LIBDAP_RPM="https://www.opendap.org/pub/binary/hyrax-${HYRAX_VERSION}/centos-7.x/libdap-${LIBDAP_VERSION}.el7.centos.x86_64.rpm"
+ENV BES_RPM="https://www.opendap.org/pub/binary/hyrax-${HYRAX_VERSION}/centos-7.x/bes-${BES_VERSION}.static.el7.centos.x86_64.rpm"
 ENV OLFS_WAR_URL="https://www.opendap.org/pub/olfs/olfs-${OLFS_VERSION}-webapp.tgz"
 
-RUN yum -y install $LIBDAP_RPM $BES_RPM
+# Install Libdap
+RUN set -e \
+    && echo "Retrieving, verifying, and installing libdap. rpm: $LIBDAP_RPM" \
+    && curl -s $LIBDAP_RPM > ./libdap.rpm \
+    && curl -s $LIBDAP_RPM.sig > ./libdap.rpm.sig \
+    && df -h \
+    && gpg -v --verify ./libdap.rpm.sig ./libdap.rpm \
+    && ls -l ./libdap* \
+    && yum -y install ./libdap.rpm 
+
+# Install BES
+RUN set -e \
+    && echo "Retrieving, verifying, and installing besd. rpm: $BES_RPM" \
+    && curl -s ${BES_RPM} > ./bes.rpm \
+    && curl -s ${BES_RPM}.sig > ./bes.rpm.sig \
+    && df -h \
+    && gpg -v --verify ./bes.rpm.sig ./bes.rpm \
+    && ls -l ./bes* \
+    && yum -y install ./bes.rpm
+    
+    # rm -f libdap.* bes.*
+
 RUN echo "besdaemon is here: "`which besdaemon`
 
 
-# Retrieve and install the OLFS web application
-RUN curl -fSL ${OLFS_WAR_URL} | tar -C /dev/shm -xzf -  && \
-    unzip -o /dev/shm/olfs-${OLFS_VERSION}-webapp/opendap.war -d ${CATALINA_HOME}/webapps/opendap/ && \
-    rm -rf /dev/shm/*
-
-# set host for bes that olfs will contact - this is expected to be over docker's internal network
-# RUN sed -i 's/localhost/besd/' ${CATALINA_HOME}/webapps/opendap/WEB-INF/conf/olfs.xml
+# Retrieve, verify, and install the OLFS web application
+RUN set -e \
+    && echo "Retrieving And Installing OLFS-${OLFS_VERSION}" \
+    && curl -sfSL ${OLFS_WAR_URL} > olfs-${OLFS_VERSION}.tgz \
+    && curl -sfSL ${OLFS_WAR_URL}.sig > olfs-${OLFS_VERSION}.tgz.sig \
+    && echo "Verifying tarball..." \
+    && gpg --verify olfs-${OLFS_VERSION}.tgz.sig olfs-${OLFS_VERSION}.tgz \
+    && echo "Unpacking tarball..." \
+    && tar -C /dev/shm -xzf olfs-${OLFS_VERSION}.tgz \
+    && echo "Unpacking warfile..." \
+    && unzip -o /dev/shm/olfs-${OLFS_VERSION}-webapp/opendap.war -d ${CATALINA_HOME}/webapps/opendap/ \
+    && echo "Cleaning up." \
+    && rm -rf /dev/shm/*
 
 # Fix ownership and access permissions
-RUN mkdir -p ${CATALINA_HOME}/webapps/opendap/WEB-INF/conf/logs && \
-    chown -R tomcat:tomcat ${CATALINA_HOME}/webapps/opendap/WEB-INF/conf/logs && \
-    chmod 700 ${CATALINA_HOME}/webapps/opendap/WEB-INF/conf/logs 
+RUN set -e \
+    && mkdir -p ${CATALINA_HOME}/webapps/opendap/WEB-INF/conf/logs \
+    && chown -R tomcat:tomcat ${CATALINA_HOME}/webapps/opendap/WEB-INF/conf/logs \
+    && chmod 700 ${CATALINA_HOME}/webapps/opendap/WEB-INF/conf/logs 
 
 
 COPY entrypoint.sh /
-RUN  chmod +x /entrypoint.sh
+RUN  set -e && chmod +x /entrypoint.sh
 ENTRYPOINT ["/entrypoint.sh"]
 
 EXPOSE 8080
@@ -57,7 +105,7 @@ EXPOSE 11002
 
 # can't use USER with entrypoint that needs root
 # use gosu or, as done, enable bes user write so the entrypoint does not need root
-RUN  chown -R bes /etc/bes
+RUN  set -e && chown -R bes /etc/bes
 USER root
 
 # tunables - to be overridden on command line or in docker-compose or ansible
