Switch el9-builds to build from `bes_core` docker image instead of RPMs (#120)
* Update el-9 shared and besd build

* update el9 hyrax

* udpate el9 ngap

* clean up

* update helper functions

* update .travis.yml to run CI on branch

* i suppose equals signs are important

* OLFS: Triggering hyrax-docker image production for el8.
Build Version Matrix:
TARGET_OS: el8
libdap4-3.21.1-390 2026-03-04T03:14:01+0000
bes-3.21.1-1096 2026-03-04T23:14:34+0000
olfs-1.18.15-726 2026-03-04T23:29:26+0000
hyrax-1.17.1-726 2026-03-04T23:29:26+0000

* OLFS: Triggering hyrax-docker image production for el9.
Build Version Matrix:
TARGET_OS: el9
TOMCAT_MAJOR_VERSION: 11
libdap4-3.21.1-390 2026-03-04T03:14:01+0000
bes-3.21.1-1096 2026-03-04T23:14:34+0000
olfs-1.18.15-727 2026-03-05T00:05:12+0000
hyrax-1.17.1-727 2026-03-05T00:05:12+0000

* OLFS: Triggering hyrax-docker image production for el8.
Build Version Matrix:
TARGET_OS: el8
libdap4-3.21.1-390 2026-03-04T03:14:01+0000
bes-3.21.1-1096 2026-03-04T23:14:34+0000
olfs-1.18.15-730 2026-03-05T17:35:18+0000
hyrax-1.17.1-730 2026-03-05T17:35:18+0000

* OLFS: Triggering hyrax-docker image production for el8.
Build Version Matrix:
TARGET_OS: el8
libdap4-3.21.1-390 2026-03-04T03:14:01+0000
bes-3.21.1-1101 2026-03-05T17:25:18+0000
olfs-1.18.15-731 2026-03-05T17:37:19+0000
hyrax-1.17.1-731 2026-03-05T17:37:19+0000

* OLFS: Triggering hyrax-docker image production for el9.
Build Version Matrix:
TARGET_OS: el9
TOMCAT_MAJOR_VERSION: 11
libdap4-3.21.1-390 2026-03-04T03:14:01+0000
bes-3.21.1-1101 2026-03-05T17:25:18+0000
olfs-1.18.15-732 2026-03-05T18:13:42+0000
hyrax-1.17.1-732 2026-03-05T18:13:42+0000

* install chkconfig for el9

* fix spelling bork

* rearrange

* update chkconfig install

* tweaks from code review

---------

Co-authored-by: Hannah Robertson <1076701+hannahilea@users.noreply.github.com>
Co-authored-by: The-Robot-Travis <npotter@opendap.org>

diff --git a/el9-builds/ngap/Dockerfile b/el9-builds/ngap/Dockerfile
--- a/el9-builds/ngap/Dockerfile
+++ b/el9-builds/ngap/Dockerfile
@@ -13,7 +13,18 @@
 # it for debugging stuff.
 #
 # Set one or more individual labels
-FROM rockylinux:9
+ARG BES_CORE_IMAGE_TAG
+FROM ${BES_CORE_IMAGE_TAG:-"rockylinux:9"}
+
+ARG BES_CORE_IMAGE_TAG
+RUN if [ -z "$BES_CORE_IMAGE_TAG" ]; then \
+        echo "Error: Non-empty BES_CORE_IMAGE_TAG must be specified. Exiting."; \
+        exit 1; \
+    fi
+
+# User defined and created in the `bes_core` image
+ENV BES_USER="${USER:-"bes_user"}"
+
 LABEL org.opencontainers.image.authors="support@opendap.org"
 USER root
 ENV DEBUG_BUILD=""
@@ -29,7 +40,7 @@ ENV java_version="java-21-openjdk"
 # 'awscli' is used by entrypoint.sh
 # 'ps' (aka procps) is used by besctl and entrypoint.sh
 # 'bc' is used entrypoint.sh and cleanup_files.sh
-ENV dnf_runtime_packages="which unzip jq procps bc"
+ENV dnf_runtime_packages="which unzip jq procps bc chkconfig"
 RUN echo "# dnf_runtime_packages: $dnf_runtime_packages"
 
 
@@ -81,25 +92,26 @@ ARG HYRAX_VERSION
 ENV HYRAX_VERSION=${HYRAX_VERSION:-"snapshot-$TARGET_OS"}
 RUN echo "# HYRAX_VERSION: ${HYRAX_VERSION}"
 
+# Fail if requested LIBDAP_VERSION or BES_VERSION do not match installations in base image
 ARG LIBDAP_VERSION
 ENV LIBDAP_VERSION="${LIBDAP_VERSION:-"snapshot"}"
-RUN echo "# LIBDAP_VERSION: $LIBDAP_VERSION"
-
-ARG LIBDAP_RPM
-ENV LIBDAP_RPM="${LIBDAP_RPM:-"libdap-$LIBDAP_VERSION.$TARGET_OS.x86_64.rpm"}"
-RUN echo "# LIBDAP_RPM: $LIBDAP_RPM"
-COPY ${LIBDAP_RPM} libdap-devel-* libdap-debuginfo-* /
-RUN ls -l /libdap-*  >&2
+RUN LIBDAP_VERSION_FOUND=$(cat libdap_VERSION); \
+    if [ "${LIBDAP_VERSION_FOUND}" == "${LIBDAP_VERSION:-missing}" ]; then \
+        echo "LIBDAP Version: ${LIBDAP_VERSION}"; \
+    else \
+        echo "Error: Expected LIBDAP_VERSION `${LIBDAP_VERSION}`, found version `${LIBDAP_VERSION_FOUND}`. Exiting."; \
+        exit 1; \
+    fi
 
 ARG BES_VERSION
 ENV BES_VERSION="${BES_VERSION:-"snapshot-$TARGET_OS"}"
-RUN echo "# BES_VERSION: $BES_VERSION"
-
-ARG BES_RPM
-ENV BES_RPM="${BES_RPM:-"bes-$BES_VERSION.static.$TARGET_OS.x86_64.rpm"}"
-RUN echo "# BES_RPM: $BES_RPM"
-COPY "$BES_RPM" bes-devel-* bes-debuginfo-* /
-RUN ls -l /bes-* >&2
+RUN BES_VERSION_FOUND=$(cat bes_VERSION); \
+    if [ "${BES_VERSION_FOUND}" == "${BES_VERSION:-missing}" ]; then \
+        echo "BES Version: ${BES_VERSION}"; \
+    else \
+        echo "Error: Expected BES_VERSION \"${BES_VERSION}\", found version \"${BES_VERSION_FOUND}\". Exiting."; \
+        exit 1; \
+    fi
 
 ARG OLFS_VERSION
 ENV OLFS_VERSION="${OLFS_VERSION:-"unknown"}"
@@ -138,6 +150,7 @@ LABEL org.opendap.hyrax.version.is-production="false"
 LABEL org.opencontainers.image.authors="support@opendap.org"
 
 USER root
+WORKDIR /
 
 ######################################################################
 # Update the OS and create a handy executable shell scipt to simplify
@@ -147,8 +160,7 @@ RUN set -e \
     && dnf update -y \
     && echo "#!/bin/bash" > /install-dev-tools \
     && echo "dnf install -y $dnf_developer_tools_packages" > /install-dev-tools \
-    && chmod 755 /install-dev-tools
-
+    && chmod 755 /install-dev-tools \
 
 ######################################################################
 # Rocky9 comes with built in curl-minimal. For our puposes we want
@@ -156,13 +168,13 @@ RUN set -e \
 # The '--allowerasing' parameter enables dnf to erase curl-minimal
 # and then install the full package.
 #
-RUN set -e \
+# RUN set -e \
     && echo "$HR" >&2 \
     && echo "# Installing cURL for developers (not minimal cURL)" >&2 \
     && dnf install -y curl curl-devel --allowerasing \
     && echo "# cURL version: $(curl --version)" >&2 \
-    && dnf clean all \
-    && echo "$HR" >&2
+    # && dnf clean all \
+    && echo "$HR" >&2 \
 
 ######################################################################
 # We want java ac ertain way ($java_version) and
@@ -174,7 +186,7 @@ RUN set -e \
 #       update-alternatives --list
 # - We're using the one we wanted:
 #       echo "# java version: $( java -version 2>&1 )"
-RUN set -e \
+# RUN set -e \
     && echo "$HR" >&2 \
     && echo "# It's Java Time Witches!" >&2 \
     && echo "# Installing $java_version" >&2 \
@@ -185,8 +197,8 @@ RUN set -e \
     && echo "# Enabled $java_version" >&2 \
     && echo "# java version: $( java -version 2>&1 )" \
     && update-alternatives --list \
-    && dnf clean all \
-    && echo "$HR" >&2
+    # && dnf clean all \
+    && echo "$HR" >&2 \
 
 ######################################################################
 # This Dockerfile brings in the Tomcat Native APR by using the one
@@ -196,7 +208,7 @@ RUN set -e \
 # We also enable the CodeReady Builder repo so we can get the
 # libtirpc-devel package.
 #
-RUN set -e \
+# RUN set -e \
     && echo "$HR" >&2 \
     # The CRB (CodeReady Builder) repository has to be enabled to get the libtirpc-devel package.
     && echo "# Installing 'dnf-plugins-core', enabling CRB (CodeReady Builder) repository and installing 'Development Tools'" >&2 \
@@ -208,16 +220,16 @@ RUN set -e \
 ######################################################################
 # Install our runtime and build time packages.
 #
-RUN set -e \
+# RUN set -e \
     && echo "$HR2" >&2 \
     && echo "# Installing NGAP package lists..." >&2 \
     && dnf install -y $dnf_runtime_packages $dnf_build_the_things_packages \
-    && dnf clean all \
-    && echo "$HR" >&2
+    # && dnf clean all \
+    && echo "$HR" >&2 \
 
 ######################################################################
 # The follow is a sanity check so that we can see what we got.
-RUN set -e \
+# RUN set -e \
     && echo "$HR" >&2  \
     && if test -n "$DEBUG_BUILD"; then \
     echo "# Sanity checking installed packages..." >&2 \
@@ -246,37 +258,39 @@ RUN set -e \
     else echo "# Skipping Sanity Checks." >&2 ; fi \
     && echo "$HR" >&2
 
-
 ################################################################
-# Install the libdap rpm
-#  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
-RUN set -e \
-    && echo "$HR" >&2 \
-    && echo "# Installing the libdap rpm: $LIBDAP_RPM" >&2 \
-    && ls -l ./libdap* \
-    && dnf -y install ./libdap-*.rpm \
-    && echo "# The 'dnf install' command exited with status: $?" >&2 \
-    && rm -f "./$LIBDAP_RPM" \
-    && dnf clean all \
-    && echo "# libdap4 is installed." >&2 \
-    && echo "$HR" >&2
+# Set up BES
+#
+# BES is already installed on the base image, but
+# we need to do some additional configuration (to match what was
+# previously handled by bes RPM installation)
 
-################################################################
-# Install the the BES
-# besd, besdaemon, beslistener, besctl, besstandalone, bescmdline
-#  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
-RUN set -e \
-    && echo "$HR" >&2 \
-    && echo "# Installing the BES rpm: $BES_RPM" >&2 \
-    && ls -l ./bes* \
-    && dnf -y install ./bes-*.rpm \
-    && echo "# The 'dnf install' command exited with status: $?" >&2 \
-    && rm -f "./$BES_RPM" \
-    && dnf clean all \
-    && echo "# besdaemon is here: $(which besdaemon)" >&2 \
-    && echo "#      besdaemon -v: '$(besdaemon -v)'" >&2 \
-    && echo "$HR" >&2
+# Add besd service to start at boot
+RUN cp ${PREFIX}/etc/rc.d/init.d/besd /etc/rc.d/init.d/besd \
+    && chkconfig --add besd \
+    && ldconfig \
+    && chkconfig --list | grep besd \
+    && echo "whoami: $(whoami)" \
+    && echo "besdaemon is here: $(which besdaemon)"
 
+# Adapted from bes/spec.all_static.in in RPM creation.
+# The four *.pem substitutions may be unnecessary, as those *.pem files may be
+# vestigial substitutions for a build process past.
+RUN sed -i.dist \
+    -e 's:=.*/bes.log:=/var/log/bes/bes.log:' \
+    -e 's:=.*/lib/bes:='"$PREFIX"'/lib/bes:' \
+    -e 's:=.*/share/bes:='"$PREFIX"'/share/bes:' \
+    -e 's:=.*/share/hyrax:='"$PREFIX"'/share/hyrax:' \
+    -e 's:=/full/path/to/serverside/certificate/file.pem:=/etc/pki/bes/cacerts/file.pem:' \
+    -e 's:=/full/path/to/serverside/key/file.pem:=/etc/pki/bes/public/file.pem:' \
+    -e 's:=/full/path/to/clientside/certificate/file.pem:=/etc/pki/bes/cacerts/file.pem:' \
+    -e 's:=/full/path/to/clientside/key/file.pem:=/etc/pki/bes/public/file.pem:' \
+    -e 's:=user_name:='"$BES_USER"':' \
+    -e 's:=group_name:='"$BES_USER"':' \
+    $PREFIX/etc/bes/bes.conf \
+    && mkdir -p "/var/log/bes/" \
+    && touch "/var/log/bes/bes.log" \
+    && sudo chown -R $BES_USER:$BES_USER "/var/log/bes/"
 
 ################################################################
 # Install the Apache-Portable-Runtime (Apache APR)
@@ -292,6 +306,7 @@ RUN set -e \
     && dnf clean all \
     && echo "Apache APR is installed." >&2 \
     && echo "$HR" >&2
+
 ################################################################
 # Install and Setup Tomcat
 #
@@ -451,7 +466,7 @@ RUN set -e \
     && echo "Retrieving, and building hyrax regression tests." >&2 \
     && echo "h_r_t will be in: $TEST_INSTALL_DIR" >&2 \
     && mkdir -p "$TEST_INSTALL_DIR" \
-    && git clone -v "https://github.com/opendap/hyrax_regression_tests" "$TEST_INSTALL_DIR" \
+    && git clone --depth 1 -v "https://github.com/opendap/hyrax_regression_tests" "$TEST_INSTALL_DIR" \
     && cd "$TEST_INSTALL_DIR" \
     && git status >&2 \
     && autoreconf -vif >&2 \
@@ -478,10 +493,4 @@ EXPOSE 8443
 EXPOSE 10022
 EXPOSE 11002
 
-# can't use USER with entrypoint that needs root
-# use gosu or, as done, enable bes user write so the entrypoint does not need root
-RUN  set -e && chown -R bes /etc/bes
-USER root
-
 CMD ["-"]
-
