added a secondary Tomcat download location incase the first is down. (#79)
* added a secondary Tomcat download location incase the first is down.

diff --git a/builds/build-rh8 b/builds/build-rh8
--- a/builds/build-rh8
+++ b/builds/build-rh8
@@ -227,32 +227,40 @@ function get_tomcat_distro(){
     local tomcat_distro="apache-tomcat-${tomcat_version}.tar.gz"
     loggy "         tomcat_distro: ${tomcat_distro}"
 
-    local tomcat_major_url="https://archive.apache.org/dist/tomcat/tomcat-${tomcat_major_version}"
-    loggy "      tomcat_major_url: ${tomcat_major_url}"
+    # Define the Tomcat download endpoints.
+    local tde1="https://downloads.apache.org/tomcat/tomcat-${tomcat_major_version}"
+    local tde2="https://archive.apache.org/dist/tomcat/tomcat-${tomcat_major_version}"
 
-    local tomcat_distro_url="${tomcat_major_url}/v${tomcat_version}/bin/${tomcat_distro}"
-    loggy "     tomcat_distro_url: ${tomcat_distro_url}"
-    local tomcat_distro_file="${target_dir}/${tomcat_distro}"
-    loggy "    tomcat_distro_file: ${tomcat_distro_file}"
+    local curl_status=1 # Fails unless it succeeded
+    local found_it=1    # 0 when found
+    for download_endpoint in "$tde2" "$tde1"
+    do
+        loggy "Trying download_endpoint: ${download_endpoint}"
 
-    local tomcat_sig_url="${tomcat_distro_url}.asc"
-    loggy "        tomcat_sig_url: ${tomcat_sig_url}"
-    local tomcat_sig_file="${tomcat_distro_file}.asc"
-    loggy "       tomcat_sig_file: ${tomcat_sig_file}"
-
-    local tomcat_keys_url="${tomcat_major_url}/KEYS"
-    loggy "       tomcat_keys_url: ${tomcat_keys_url}"
-    local tomcat_keys_file="${target_dir}/apache_tomcat_keys"
-    loggy "      tomcat_keys_file: ${tomcat_keys_file}"
-
-    loggy ""
-    loggy "       cURL retrieving: ${tomcat_distro_url}"
-    curl ${silent} -o "${tomcat_distro_file}" "${tomcat_distro_url}"
-    if test $? -ne 0; then
-        echo "ERROR! Failed to retrieve Tomcat distribution from ${tomcat_distro_url}" >&2
+        local tomcat_distro_url="${download_endpoint}/v${tomcat_version}/bin/${tomcat_distro}"
+        loggy "       tomcat_distro_url: ${tomcat_distro_url}"
+        local tomcat_distro_file="${target_dir}/${tomcat_distro}"
+        loggy "      tomcat_distro_file: ${tomcat_distro_file}"
+        loggy "         cURL retrieving: ${tomcat_distro_url}"
+        curl ${silent} -o "${tomcat_distro_file}" "${tomcat_distro_url}"
+        curl_status=$?
+        if test $curl_status -ne 0; then
+            echo "WARNING! cURL Failed to retrieve Tomcat distribution. curl_status: $curl_status url: ${tomcat_distro_url}" >&2
+        else
+            found_it=0
+            break
+        fi
+    done
+    if test $found_it -ne 0 ; then
+        echo "ERROR! cURL Failed to retrieve Tomcat distribution." >&2
         return 2
     fi
 
+    loggy ""
+    local tomcat_sig_url="${tomcat_distro_url}.asc"
+    loggy "          tomcat_sig_url: ${tomcat_sig_url}"
+    local tomcat_sig_file="${tomcat_distro_file}.asc"
+    loggy "         tomcat_sig_file: ${tomcat_sig_file}"
     loggy ""
     loggy "       cURL retrieving: ${tomcat_sig_url}"
     curl ${silent} -o "${tomcat_sig_file}" "${tomcat_sig_url}"
@@ -261,6 +269,10 @@ function get_tomcat_distro(){
         return 2
     fi
 
+    local tomcat_keys_url="${download_endpoint}/KEYS"
+    loggy "         tomcat_keys_url: ${tomcat_keys_url}"
+    local tomcat_keys_file="${target_dir}/apache_tomcat_keys"
+    loggy "        tomcat_keys_file: ${tomcat_keys_file}"
     loggy ""
     loggy "       cURL retrieving: ${tomcat_keys_url}"
     curl ${silent} -o "${tomcat_keys_file}" "${tomcat_keys_url}"
@@ -278,7 +290,6 @@ function get_tomcat_distro(){
         echo "ERROR! Failed to import Tomcat public keys!" >&2
         return 2
     fi
-
     loggy ""
     loggy "Verifying Tomcat distribution:"
     loggy "    Tomcat public keys: ${tomcat_keys_file}"
