wip

diff --git a/utils/test-rh8 b/utils/test-rh8
--- a/utils/test-rh8
+++ b/utils/test-rh8
@@ -2,23 +2,21 @@
 HR="#######################################################################"
 ###########################################################################
 # loggy()
-function loggy(){
-    echo  "$@" | awk '{ print "# "$0;}'  >&2
+function loggy() {
+    echo "$@" | awk '{ print "# "$0;}' >&2
 }
 
 ###########################################################################
 # Remove all containers
-function drmac(){
-    docker rm -f $(docker ps -aq);
+function drmac() {
+    docker rm -f $(docker ps -aq)
 }
 
 ###########################################################################
 # Remove all images
-function drmai(){
-    docker rmi -f $(docker images -q);
+function drmai() {
+    docker rmi -f $(docker images -q)
 }
-
-
 
 ###########################################################################
 # use_branch()
@@ -41,8 +39,7 @@ function use_branch() {
     git fetch -v --depth=1
     git checkout "$branch"
     status=$?
-    if test $status -ne 0
-    then
+    if test $status -ne 0; then
         loggy "ERROR! Failed to checkout branch '$branch' for repository: '$repo'"
         cd "$start_dir"
         exit $status
@@ -63,7 +60,7 @@ function clean_and_get_repo() {
     # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     # cleanup repo from previous efforts
     loggy "$prolog Cleaning $host_target"
-    loggy "$prolog Removed $( rm -vrf $host_target | wc -l ) files."
+    loggy "$prolog Removed $(rm -vrf $host_target | wc -l) files."
 
     # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     # Clone fresh repo
@@ -72,8 +69,7 @@ function clean_and_get_repo() {
     loggy "$prolog Cloning $repo_url"
     git clone --depth 1 "$repo_url" "$host_target"
 
-    if test -n "$branch_name"
-    then
+    if test -n "$branch_name"; then
         use_branch "$host_target" "$branch_name"
     fi
 }
@@ -113,8 +109,7 @@ function build_libdap_for_rh8() {
     local build_script="/root/travis/travis/build-rh8-rpm.sh"
     loggy "$prolog build_script (inside docker image): $build_script"
 
-    if test -n "$clean"
-    then
+    if test -n "$clean"; then
         clean_and_get_repo "$repo_name" "$branch_name" "$host_target"
     fi
 
@@ -173,14 +168,12 @@ function build_hyrax_dependencies_for_rh8() {
     loggy "$prolog Using Docker Image: $image"
 
     local build_script=""
-    if test -z "$interactive"
-    then
+    if test -z "$interactive"; then
         build_script="$docker_target/build-for-rocky8.sh"
     fi
     loggy "$prolog build_script (inside docker image): $build_script"
 
-    if test -n "$clean"
-    then
+    if test -n "$clean"; then
         clean_and_get_repo "$repo_name" "$branch_name" "$host_target"
     fi
 
@@ -194,10 +187,9 @@ function build_hyrax_dependencies_for_rh8() {
         --env BUILD_NUMBER=666 \
         $image $build_script
     status=$?
-    if test $status -ne 0
-    then
+    if test $status -ne 0; then
         loggy "$prolog ERROR! Docker run command failed! status: $status"
-        return $status;
+        return $status
     fi
 
     loggy "$prolog Packaging results..."
@@ -213,7 +205,115 @@ function build_hyrax_dependencies_for_rh8() {
     loggy "$prolog END"
 }
 
+###########################################################################
+# build_bes_rpms_for_rhel8()
+#
+# From the bes/.travis.yml
+#- stage: build-and-package
+#  name: "Enterprise Linux 8 RPMs (via Rocky8)"
+#  script:
+#    - export BES_BUILD=rocky8
+#    - mkdir -p $prefix/rpmbuild
+#    - echo "branch name ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}"
+#    - docker run
+#      --env prefix=/root/install
+#      --volume $prefix/rpmbuild:/root/rpmbuild
+#      --volume $TRAVIS_BUILD_DIR:/root/travis
+#      --env GDAL_OPTION=$GDAL_OPTION
+#      --env OS=rocky8
+#      --env DIST=el8
+#      --env LIBDAP_RPM_VERSION=$LIBDAP_RPM_VERSION
+#      --env BES_BUILD_NUMBER=$BES_BUILD_NUMBER
+#      --env AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
+#      --env AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
+#      opendap/rocky8_hyrax_builder:latest /root/travis/travis/build-rh8-rpm.sh
+#
+function build_bes_rpms_for_rhel8() {
+    local prolog="build_bes_for_ubuntu() -"
+    loggy "$HR"
+    loggy "$prolog BEGIN"
+    local branch_name="${1:-"master"}"
+    loggy "$prolog branch_name: $branch_name"
+
+    local clean="${2:-""}"
+    loggy "$prolog clean: '$clean'"
+
+    local interactive="${3:-""}"
+    loggy "$prolog interactive: '$interactive'"
+    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+    # configuration
+
+    local repo_name="bes"
+    loggy "$prolog Using repo_name: $repo_name"
+
+    local top_dir
+    top_dir="$PWD"
+
+    local host_target
+    host_target="$top_dir/$repo_name"
+    loggy "$prolog Using host_target: $host_target"
+
+    if test -n "$clean" || ! test -d "$host_target"; then
+        clean_and_get_repo "$repo_name" "$branch_name" "$host_target"
+    fi
+
+    local host_result_dir
+    host_result_dir="$top_dir/install"
+    loggy "$prolog Using host_result_dir: $host_result_dir"
+    mkdir -vp "$host_result_dir"
+
+    get_bes_dependencies "" "" ""
+
+    local docker_target="/root/$repo_name"
+    loggy "$prolog Using docker_target: $docker_target"
+
+    local docker_result_dir="/root/install"
+    loggy "$prolog Using docker_result_dir: $docker_result_dir"
+
+    local image="opendap/rocky8_hyrax_builder:latest"
+    loggy "$prolog Using Docker Image: $image"
+
+    # /root/bes/travis/build-rh8-rpm.sh
+    local build_script_name="build-rh8-rpm.sh"
+    local docker_run_script="/root/travis/$build_script_name"
+    loggy "$prolog build_script (used inside docker image): '$build_script_name'"
+    if test -n "$interactive"; then
+        loggy "$prolog This is an interactive deployment, no build script used."
+        docker_run_script=""
+    fi
+
+    if test -n "$clean"; then
+        clean_and_get_repo "$repo_name" "$branch_name" "$host_target"
+    fi
+
+    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+    # Build it
+    loggy "$prolog Starting docker. Image: $image"
+    docker run -it \
+        --volume "$host_target":"$docker_target" \
+        --volume "$host_result_dir":"$docker_result_dir" \
+        --env prefix="$docker_result_dir" \
+        --env BUILD_NUMBER=666 \
+        "$image" $docker_run_script
+
+    status=$?
+    if test $status -ne 0; then
+        loggy "$prolog ERROR! Docker run command failed! status: $status"
+        return $status
+    fi
+
+    loggy "$prolog Packaging results. result_bundle: $result_bundle"
+    mkdir -p $host_target/package
+    tar -C $top_dir -czvf $result_bundle install
+    loggy "$prolog "
+    loggy "$prolog Produced dependencies tar file: "
+    loggy "$(ls -l $result_bundle)"
+    loggy "$prolog "
+    loggy "$prolog Inventory: "
+    loggy "$(tar -tf $result_bundle)"
+    loggy "$prolog"
+    loggy "$prolog END"
+}
 
 # build_libdap_for_rh8 "" ""
 # build_hyrax_dependencies_for_rh8 RHEL9 c
-
