wip

diff --git a/utils/test-rh8 b/utils/test-rh8
--- a/utils/test-rh8
+++ b/utils/test-rh8
@@ -40,6 +40,14 @@ function use_branch() {
     git remote set-branches origin '*'
     git fetch -v --depth=1
     git checkout "$branch"
+    status=$?
+    if test $status -ne 0
+    then
+        loggy "ERROR! Failed to checkout branch '$branch' for repository: '$repo'"
+        cd "$start_dir"
+        exit $status
+    fi
+
     cd "$start_dir"
     loggy "$prolog END (pwd: $PWD)"
 }
@@ -196,6 +204,5 @@ function build_hyrax_dependencies_for_rh8() {
 
 
 # build_libdap_for_rh8 "" ""
-
 # build_hyrax_dependencies_for_rh8 RHEL9 c
 
diff --git a/utils/test-rh9 b/utils/test-rh9
--- a/utils/test-rh9
+++ b/utils/test-rh9
@@ -40,6 +40,13 @@ function use_branch() {
     git remote set-branches origin '*'
     git fetch -v --depth=1
     git checkout "$branch"
+    status=$?
+    if test $status -ne 0
+    then
+        loggy "ERROR! Failed to checkout branch '$branch' for repository: '$repo'"
+        cd "$start_dir"
+        exit $status
+    fi
     cd "$start_dir"
     loggy "$prolog END (pwd: $PWD)"
 }
