Added check for the Hyrax version label in the docker image

diff --git a/travis/regression_test_script b/travis/regression_test_script
--- a/travis/regression_test_script
+++ b/travis/regression_test_script
@@ -263,18 +263,26 @@ function check_version() {
     loggy "$HR0"
     loggy "$prolog BEGIN"
 
-    local end_point_url="$1"
+    local d_id="$1"
+    if test -z "$d_id"; then
+        loggy "$prolog ERROR! You must pass valid docker id as parameter 1"
+        return 1
+    fi
+
+    local end_point_url="$2"
     if test -z "$end_point_url"; then
-        loggy "$prolog ERROR! You must pass a Hyrax endpoint url string as parameter 1"
-        return 1
+        loggy "$prolog ERROR! You must pass a Hyrax endpoint url string as parameter 2"
+        return 2
     fi
 
-    local expected_hyrax_version="$2"
+    local expected_hyrax_version="$3"
     if test -z "$expected_hyrax_version"; then
-        loggy "$prolog ERROR! You must pass a Hyrax endpoint url string as parameter 1"
-        return 1
+        loggy "$prolog ERROR! You must pass a Hyrax endpoint url string as parameter 3"
+        return 3
     fi
 
+    local docker_version_label
+    local docker_version_status
     local version_url
     local version_response
     local hyrax_version_value
@@ -307,6 +315,26 @@ function check_version() {
         in this production environment!"
         return 1
     fi
+    loggy "$HR1"
+    loggy "$prolog Checking docker image metadata for correct Hyrax version..."
+    local version_label_key="org.opendap.hyrax.version"
+    docker_version_label=$(docker inspect --format="{{ index .Config.Labels \"$version_label_key\" }}" "$d_id")
+    docker_version_status=$?
+    loggy "docker_version_label: '$docker_version_label' docker_version_status: $docker_version_status"
+
+    if test "$expected_hyrax_version" == "$docker_version_label"; then
+        loggy "$prolog SUCCESS!
+        The Hyrax version value returned by the tested docker image inspect response
+        matches the expected_hyrax_version value."
+    else
+        loggy "$prolog ERROR!
+        The value of the hyrax version string '$docker_version_label' found in the docker
+        inspect response does not match the expected_hyrax_version env value '$expected_hyrax_version'
+        in this production environment!"
+        return 1
+    fi
+
+
     loggy "$prolog END"
     loggy "$HR0"
     return 0
@@ -455,7 +483,7 @@ function run_the_tests() {
     loggy "$prolog wait_for_hyrax status: $wait_for_hyrax_status"
     if test $wait_for_hyrax_status -ne 0; then exit $wait_for_hyrax_status; fi
 
-    check_version "$HYRAX_END_POINT" "$EXPECTED_HYRAX_VERSION"
+    check_version "$DOCKER_ID" "$HYRAX_END_POINT" "$EXPECTED_HYRAX_VERSION"
     local check_version_status=$?
     loggy "$prolog check_version status: $check_version_status"
     if test $check_version_status -ne 0; then exit $check_version_status; fi
