Adding a test for the injected hyrax version number.

diff --git a/travis/regression_test_script b/travis/regression_test_script
--- a/travis/regression_test_script
+++ b/travis/regression_test_script
@@ -9,8 +9,8 @@ HR1="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"
 HR2="--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---"
 #############################################################################
 # loggy()
-function loggy(){
-    echo  "$@" | awk '{ print "# "$0;}'  >&2
+function loggy() {
+    echo "$@" | awk '{ print "# "$0;}' >&2
 }
 prolog="$0() -"
 loggy "$HR0"
@@ -133,7 +133,9 @@ function waitForHyrax() {
     return 0
 }
 
-function clean_and_start(){
+#############################################################################
+# clean_and_start()
+function clean_and_start() {
     local prolog="clean_and_start_docker() -"
     loggy "$prolog $HR1"
     loggy "$prolog BEGIN"
@@ -147,8 +149,8 @@ function clean_and_start(){
     # Dump all other containers
     containers=$(docker ps -aq)
     if test -n "${containers}"; then
-        loggy  "$prolog Removing containers: ${containers}"
-        loggy  "$(docker rm -f ${containers})"
+        loggy "$prolog Removing containers: ${containers}"
+        loggy "$(docker rm -f ${containers})"
     fi
 
     loggy "$prolog Starting: $d_id"
@@ -156,8 +158,6 @@ function clean_and_start(){
     loggy "$prolog Started container: $container_id"
     loggy "$prolog END"
 }
-
-
 
 d_id="hyrax"
 
@@ -170,6 +170,16 @@ loggy "$prolog Retrieving Hyrax Version Response from: '$version_url'"
 version_response="$(curl -s -c cookies -b cookies -n "$netrc_file" -L "$version_url")"
 loggy "$prolog Hyrax Version Response:"
 loggy "$version_response"
+
+#   Get this line from the version response <Hyrax version="##########" /> and get the actual value of ##########
+hyrax_version_str="$(echo "$version_response" | grep "<Hyrax version" | awk '{split($0, a, "\""); print a[2];}')"
+echo "hyrax_version_str: $hyrax_version_str"
+if test "$HYRAX_VERSION" != "$hyrax_version_str"
+then
+    loggy "ERROR! The retrieved hyrax version string ($hyrax_version_str) does not match the HYRAX_VERSION ($HYRAX_VERSION) in the production environment!"
+    loggy "ERROR! Exiting process."
+    exit 1;
+fi
 loggy "$HR1"
 
 loggy "$prolog Testing image: ${test_image_name}"
@@ -193,8 +203,7 @@ loggy "$prolog rt_dir: $rt_dir"
 loggy "$prolog Creating host directory '$PWD/$rt_dir' for docker run reggression test results."
 mkdir -vp "$rt_dir"
 
-for name in testsuite.log testsuite.dir
-do
+for name in testsuite.log testsuite.dir; do
     source_name="$d_id:/hyrax_regression_tests/$name"
     target_name="$rt_dir/$name"
     loggy "$prolog AWS S3: Copying '$source_name' to '$target_name'"
