Working hyrax el9 docker

diff --git a/travis/regression_test_script b/travis/regression_test_script
--- a/travis/regression_test_script
+++ b/travis/regression_test_script
@@ -115,14 +115,15 @@ function waitForHyrax() {
             exit 1
         fi
     done
-    loggy "$prolog "
+    loggy ""
+    # Now we can fail on errors again.
+    set -e
+    loggy "$prolog Hyrax has arrived!"
     loggy "$prolog $HR2"
     loggy "$prolog Start-up Docker logs: "
     loggy "$(docker logs "$docker_id")"
     loggy "$prolog $HR2"
-    # Now we can fail on errors again.
-    set -e
-    loggy "$prolog Hyrax has arrived!"
+
     return 0
 }
 
