Change the Hyrax build numbers to be set by hyrax-docker travis jobs (#126)
* Made changes so that hyrax-docker production code injects the  Hyrax build numbers into the OLFS component of the docker images.

diff --git a/travis/regression_test_script b/travis/regression_test_script
--- a/travis/regression_test_script
+++ b/travis/regression_test_script
@@ -9,8 +9,8 @@ HR1="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"
 HR2="--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---"
 #############################################################################
 # loggy()
-function loggy(){
-    echo  "$@" | awk '{ print "# "$0;}'  >&2
+function loggy() {
+    echo "$@" | awk '{ print "# "$0;}' >&2
 }
 prolog="$0() -"
 loggy "$HR0"
@@ -133,7 +133,9 @@ function waitForHyrax() {
     return 0
 }
 
-function clean_and_start(){
+#############################################################################
+# clean_and_start()
+function clean_and_start() {
     local prolog="clean_and_start_docker() -"
     loggy "$prolog $HR1"
     loggy "$prolog BEGIN"
@@ -147,8 +149,8 @@ function clean_and_start(){
     # Dump all other containers
     containers=$(docker ps -aq)
     if test -n "${containers}"; then
-        loggy  "$prolog Removing containers: ${containers}"
-        loggy  "$(docker rm -f ${containers})"
+        loggy "$prolog Removing containers: ${containers}"
+        loggy "$(docker rm -f ${containers})"
     fi
 
     loggy "$prolog Starting: $d_id"
@@ -157,20 +159,43 @@ function clean_and_start(){
     loggy "$prolog END"
 }
 
-
-
 d_id="hyrax"
 
 clean_and_start "$d_id" "$test_image_name"
 waitForHyrax "$d_id"
 
 loggy "$HR1"
+version_url="$end_point/hyrax/version"
+loggy "$prolog Retrieving Hyrax Version Response from: '$version_url'"
+version_response="$(curl -s -c cookies -b cookies -n "$netrc_file" -L "$version_url")"
+loggy "$prolog Hyrax Version Response:"
+loggy "$version_response"
+
+#########################################################################################################
+# Verify Hyrax Version Injection
+#   Get this line from the version response:
+#       <Hyrax version="##########" />
+#   and then use awk to get the actual value of ##########
+hyrax_version_value="$(echo "$version_response" | grep "<Hyrax version" | awk '{split($0, a, "\""); print a[2];}')"
+if test "$HYRAX_VERSION" == "$hyrax_version_value"
+then
+    loggy "$prolog The Hyrax version value returned by the tested docker image matches the HYRAX_VERSION from the production environment."
+    loggy "$prolog hyrax_version_response: $hyrax_version_value"
+    loggy "$prolog          HYRAX_VERSION: $HYRAX_VERSION"
+else
+    loggy "$prolog ERROR! The returned hyrax version string ($hyrax_version_value) does not match the HYRAX_VERSION ($HYRAX_VERSION) in the production environment!"
+    loggy "$prolog ERROR! Exiting process."
+    exit 1;
+fi
+loggy "$HR1"
+#########################################################################################################
+
 loggy "$prolog Testing image: ${test_image_name}"
 set -x
 
 # If the regression tests fail we want the logs, so don't exit on fail right here
 set +e
-docker exec -it $d_id /bin/bash -c "cd hyrax_regression_tests; ./testsuite --hyraxurl=\"${end_point}\" ${netrc_file} ${tests};"
+docker exec -it $d_id /bin/bash -c "cd hyrax_regression_tests; ./testsuite --hyraxurl=\"$end_point\" $netrc_file $tests;"
 test_status=$?
 set -e
 # http_url https_url stdout testsuite.log
@@ -186,8 +211,7 @@ loggy "$prolog rt_dir: $rt_dir"
 loggy "$prolog Creating host directory '$PWD/$rt_dir' for docker run reggression test results."
 mkdir -vp "$rt_dir"
 
-for name in testsuite.log testsuite.dir
-do
+for name in testsuite.log testsuite.dir; do
     source_name="$d_id:/hyrax_regression_tests/$name"
     target_name="$rt_dir/$name"
     loggy "$prolog AWS S3: Copying '$source_name' to '$target_name'"
@@ -206,7 +230,7 @@ loggy "$prolog Acquiring bes.log from docker image."
 docker cp $d_id:/var/log/bes/bes.log .
 
 loggy "$prolog Acquiring beslog2json.py from docker image."
-docker cp $d_id:${BES_PREFIX}/bin/beslog2json.py $(pwd)/beslog2json.py
+docker cp $d_id:${BES_PREFIX}/bin/beslog2json.py "$(pwd)/beslog2json.py"
 ls -l ./beslog2json.py
 
 loggy "$HR2"
