WIP

diff --git a/travis/regression_test_script b/travis/regression_test_script
--- a/travis/regression_test_script
+++ b/travis/regression_test_script
@@ -1,5 +1,7 @@
 #!/bin/bash
 set -e
+#############################################################################
+# regression_test_script
 #
 # Travis invocation: ./travis/regression_test_script -i "$SNAPSHOT_IMAGE_TAG"
 #
@@ -11,6 +13,9 @@ HR2="--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---"
 function loggy() {
     echo "$@" | awk '{ print "# "$0;}' >&2
 }
+
+#############################################################################
+# Configuration & Command line all inline
 
 default_time_out=30
 default_image_name="opendap/hyrax:snapshot-el8"
@@ -24,7 +29,8 @@ NETRC_FILE=""
 TEST_NAMES=""
 TESTS_LOG_BASE="$default_tests_log_base"
 DOCKER_ID="hyrax"
-EXPECTED_HYRAX_VERSION="${HYRAX_WEB_UI_VERSION:-"1.17.1-933"}"
+
+EXPECTED_HYRAX_VERSION="${HYRAX_WEB_UI_VERSION:-"HYRAX_WEB_UI_VERSION-NOT-FOUND-IN-ENV"}"
 
 while getopts "ht:i:e:n:l:V:" OPTION; do
     case $OPTION in
@@ -59,6 +65,35 @@ done
 
 shift $(($OPTIND - 1))
 TEST_NAMES="$@"
+
+#############################################################################
+# show_docker_logs()
+#
+function show_docker_logs(){
+    local prolog="show_docker_logs()"
+    loggy "$prolog - BEGIN"
+
+    local docker_id="$1"
+    if test -z "$docker_id"
+    then
+        loggy "$prolog - ERROR!
+        You must supply the docker container is the first parameter to the show_docker_logs() function."
+        return 2;
+    fi
+    local docker_startup_logs
+
+    docker_startup_logs="$(docker logs "$docker_id" 2>&1)"
+    status=$?
+    if test  $status -ne 0
+    then
+        loggy "$prolog - ERROR!
+        Failed to acquire the docker logs for container: '$docker_id'"
+        return 2;
+    fi
+    echo "$docker_startup_logs" | awk -v prolog="$prolog" '{print "# " prolog "    "$0;}' >&2
+    # loggy "$docker_startup_logs" # By default, this should return the whole thing
+    loggy "$prolog - END"
+}
 
 #############################################################################
 # wait_for_hyrax()
@@ -115,18 +150,13 @@ function wait_for_hyrax() {
                 done_flag="yup"
             fi
         fi
-        # Capture SECONDS in an env var so we can evaluate and display a single value.
+        # Capture SECONDS in the 'elapsed' envar so we can evaluate and display a single value.
         elapsed=$SECONDS
-        if [ $elapsed -gt $TIME_OUT_SECONDS ]; then
-            echo "" >&2
-            loggy "$prolog $HR1"
-            loggy "$prolog $HR1"
+        if [ $elapsed -ge $TIME_OUT_SECONDS ]; then
+            echo "" >&2 # Because all those dang '.' characters from above gotta have a new line.
             loggy "$prolog ERROR: Hyrax FAILED To Start! Waited for $elapsed seconds"
-            loggy "$prolog docker logs: "
-            loggy "$(docker logs "$docker_id" 2>&1 )"
-            loggy "$prolog $HR1"
-            loggy "$prolog $HR1"
-            loggy "$prolog ERROR! Hyrax failed to start!"
+            show_docker_logs "$docker_id"
+            loggy "$prolog ERROR! Hyrax FAILED to start!"
             loggy "$prolog $HR0"
             return 1
         fi
@@ -135,12 +165,7 @@ function wait_for_hyrax() {
     # Now we can fail on errors again.
     set -e
     loggy "$prolog Hyrax Is Running!"
-    docker_startup_logs="$(docker logs "$docker_id" 2>&1)"
-    loggy "$prolog Docker logs (BEGIN):"
-    loggy "$prolog $HR1"
-    loggy "$docker_startup_logs" # By default, this should return the whole thing
-    loggy "$prolog $HR1"
-    loggy "$prolog Docker logs (END)"
+    show_docker_logs "$docker_id"
     loggy "$prolog END"
     loggy "$HR0"
 
@@ -214,7 +239,7 @@ function check_version(){
     local hyrax_version_value
     version_url="$end_point_url/hyrax/version"
 
-    #####################################################################################################
+    #####################################################
     # Get Hyrax version response from the running server
     loggy "$prolog Retrieving Hyrax Version Response from: '$version_url'"
     version_response="$(curl -s -c cookies -b cookies -n $NETRC_FILE -L "$version_url")"
@@ -222,7 +247,7 @@ function check_version(){
     loggy "$version_response"
     loggy "$HR1"
 
-    ####################################################################################################
+    ############################################################
     # Verify Hyrax Version Injection
     #   Get this line from the version response:
     #       <Hyrax version="##########" />
@@ -384,7 +409,7 @@ function test_beslog2json(){
 # Run the script is invoked as an application, otherwise source it into the current shell.
 #
 
-prolog="regression_test_script -"
+prolog="regression_test_script[] -"
 loggy "$HR0"
 loggy "$prolog BEGIN"
 loggy "$prolog Using the following configuration:"
