wip

diff --git a/travis/regression_test_script b/travis/regression_test_script
--- a/travis/regression_test_script
+++ b/travis/regression_test_script
@@ -287,9 +287,9 @@ function check_version() {
     local version_url
     local version_response
     local hyrax_version_value
-    version_url="$end_point_url/hyrax/version"
-    contents_url="$end_point_url/hyrax/contents.html"
-    ifh_url="$end_point_url/hyrax/data/nc/fnoc1.nc.dmr.html"
+    local version_url="$end_point_url/hyrax/version"
+    local contents_url="$end_point_url/hyrax/contents.html"
+    local ifh_url="$end_point_url/hyrax/data/nc/fnoc1.nc.dmr.html"
 
     #####################################################
     # Get Hyrax version response from the running server
@@ -309,7 +309,7 @@ function check_version() {
     loggy "$prolog expected_hyrax_version: $expected_hyrax_version"
     if test "$expected_hyrax_version" == "$hyrax_version_value"; then
         loggy "$prolog SUCCESS!
-        The Hyrax version returned by the Hyrax version response from the tested docker image matches the
+        The value of the Hyrax version returned in the Hyrax version response from the tested docker image matches the
         expected_hyrax_version value."
     else
         loggy "$prolog ERROR!
@@ -323,8 +323,7 @@ function check_version() {
     local version_label_key="org.opendap.hyrax.version"
     docker_version_label=$(docker inspect --format="{{ index .Config.Labels \"$version_label_key\" }}" "$d_id")
     docker_version_status=$?
-    loggy "docker_version_label: '$docker_version_label' docker_version_status: $docker_version_status"
-
+    loggy "docker_version_label: '$docker_version_label'"
     if test "$expected_hyrax_version" = "$docker_version_label"; then
         loggy "$prolog SUCCESS!
         The 'docker inspect' command for $d_id returned the expected_hyrax_version value."
@@ -337,7 +336,6 @@ function check_version() {
     fi
 
     local deployment_context="opendap"
-
     local some_page
     if test "$DOCKER_NAME" = "ngap"
     then
@@ -345,8 +343,15 @@ function check_version() {
         loggy "$HR1"
         loggy "$prolog Checking NGAP landing page for correct Hyrax version."
         some_page="$(docker exec -it $d_id bash -c "cat /usr/share/tomcat/webapps/$deployment_context/docs/ngap/ngap.html")"
-        loggy "$prolog NGAP Landing Page: "
-        loggy "$some_page"
+        # loggy "$prolog NGAP Landing Page: "
+        # loggy "$some_page"
+        echo "$some_page" | grep "$expected_hyrax_version"
+        status=$?
+        if test $status -ne 0
+        then
+            loggy "$prolog ERROR! The expected version string as not found in the version.xsl file."
+            return  $status
+        fi
     fi
 
     loggy "$HR1"
@@ -360,8 +365,8 @@ function check_version() {
     loggy "$HR1"
     loggy "$prolog Checking version.xsl for correct Hyrax version, d_id: $d_id"
     some_page="$(docker exec -it "$d_id" bash -c "cat /usr/share/tomcat/webapps/$deployment_context/xsl/version.xsl")"
-    loggy "$prolog version.xsl: "
-    loggy "$some_page"
+    #loggy "$prolog version.xsl: "
+    #loggy "$some_page"
     echo "$some_page" | grep "$expected_hyrax_version"
     status=$?
     if test $status -ne 0
@@ -376,8 +381,8 @@ function check_version() {
     loggy "$HR1"
     loggy "$prolog Checking contents.html for correct Hyrax version."
     some_page="$(curl -s -c cookies -b cookies -n $NETRC_FILE -L "$contents_url")"
-    loggy "$prolog $contents_url: "
-#    loggy "$some_page"
+    # loggy "$prolog $contents_url: "
+    # loggy "$some_page"
     echo "$some_page" | grep "$expected_hyrax_version"
     status=$?
     if test $status -ne 0
@@ -392,8 +397,8 @@ function check_version() {
     loggy "$HR1"
     loggy "$prolog Checking DAP4 Data Request Form page for correct version."
     some_page="$(curl -s -c cookies -b cookies -n $NETRC_FILE -L "$ifh_url")"
-    loggy "$prolog $ifh_url: "
-#    loggy "$some_page"
+    # loggy "$prolog $ifh_url: "
+    # loggy "$some_page"
     echo "$some_page" | grep "$expected_hyrax_version"
     status=$?
     if test $status -ne 0
