Testing a simplification.

diff --git a/travis/version_testsuite b/travis/version_testsuite
--- a/travis/version_testsuite
+++ b/travis/version_testsuite
@@ -10,13 +10,13 @@ function loggy() {
 }
 
 #########################################################################################################
-# test_image_label()
+# test_docker_image_label()
 #     Looks at the metadata of docker image 'd_id' ($1) using docker 'inspect'
 #     to retrieve the value of 'label_key' ($2) from the docker .Config.Labels
 #     The retrieved value is compared with the 'expected_value' ($3)
 #
-function test_image_label(){
-    local prolog="test_image_label() -"
+function test_docker_image_label() {
+    local prolog="test_docker_image_label() -"
     loggy "$HR2"
     loggy "$prolog BEGIN"
 
@@ -53,12 +53,12 @@ function test_image_label(){
 }
 
 #########################################################################################################
-# test_file_in_image()
+# test_file_in_docker_image()
 #     Looks inside docker image 'd_id' ($1) in the file
 #     named file_path ($2) for the string 'expected_value' ($3)
 #
-function test_file_in_image() {
-    local prolog="check_file_in_image() -"
+function test_file_in_docker_image_OLD() {
+    local prolog="test_file_in_docker_image() -"
     loggy "$HR2"
     loggy "$prolog BEGIN"
 
@@ -75,12 +75,11 @@ function test_file_in_image() {
     # loggy "$some_file"
     echo "$some_file" | grep "$expected_value"
     status=$?
-    if test $status -ne 0
-    then
+    if test $status -ne 0; then
         loggy "$prolog ERROR! The expected value '$expected_value' was not found in the file '$file_path'"
         loggy "$prolog $d_id::$file_path: "
         loggy "$some_file"
-        return  $status
+        return $status
     else
         loggy "$prolog SUCCESS! Found it!"
     fi
@@ -88,6 +87,45 @@ function test_file_in_image() {
     loggy "$HR2"
     return 0
 }
+#########################################################################################################
+# test_file_in_docker_image()
+#     Looks inside docker image 'd_id' ($1) in the file
+#     named file_path ($2) for the string 'expected_value' ($3)
+#
+function test_file_in_docker_image() {
+    local prolog="test_file_in_docker_image() -"
+    loggy "$HR2"
+    loggy "$prolog BEGIN"
+
+    local d_id="$1"
+    local file_path="$2"
+    local expected_value="$3"
+
+    local status
+    local some_file
+
+    loggy "$prolog Checking for '$expected_value' in '$d_id::$file_path'"
+    # some_file="$(docker exec -it "$d_id" bash -c "cat \"$file_path\"")"
+    some_file="$(docker run --rm --entrypoint cat "$d_id" "$file_path")"
+
+    # loggy "$prolog $d_id::$file_path: "
+    # loggy "$some_file"
+    echo "$some_file" | grep "$expected_value"
+    status=$?
+    if test $status -ne 0; then
+        loggy "$prolog ERROR! The expected value '$expected_value' was not found in the file '$file_path'"
+        loggy "$prolog $d_id::$file_path: "
+        loggy "$some_file"
+        return $status
+    else
+        loggy "$prolog SUCCESS! Found it!"
+    fi
+    loggy "$prolog END"
+    loggy "$HR2"
+    return 0
+}
+#docker cp $CONTAINER_ID:/path/in/container /path/on/host
+
 #########################################################################################################
 # check_version()
 #     Verify that we have the expected server version
@@ -103,81 +141,45 @@ function check_version() {
     fi
     loggy "$prolog                   d_id: $d_id"
 
-    local d_id="$1"
-    if test -z "$d_id"; then
-        loggy "$prolog ERROR! You must pass valid docker id as parameter 1"
-        return 1
-    fi
-    loggy "$prolog                   d_id: $d_id"
-
-
-
-
-
-
-
     local status
-
-
-
-    #################################################################################################
-    # Target specific tweaking using global values
-    # @TODO - refactor and move upstream where possible
-    local version_label_key="org.opendap.hyrax.version"
-    local expected_version_str="$HYRAX_WEB_UI_VERSION"
-    if test "$DOCKER_NAME" = "besd"
-    then
-        version_label_key="org.opendap.$DOCKER_NAME.version"
-        expected_version_str="$BES_VERSION"
-    fi
-    if test "$DOCKER_NAME" = "olfs"
-    then
-        version_label_key="org.opendap.$DOCKER_NAME.version"
-        expected_version_str="$OLFS_VERSION"
-    fi
-
-
-    local version_label_key="org.opendap.$DOCKER_DIR.version"
-
-
-
-
-
-
-
-    loggy "$prolog      version_label_key: $version_label_key"
-    loggy "$prolog   expected_version_str: $expected_version_str"
-
-    #################################################################
-    # The check the docker image metadata (in .Config.Labels) for
-    # our version information.
-    test_image_label "$d_id" "$version_label_key" "$expected_version_str"
-    status=$?
-    if test $status -ne 0
-    then
-        loggy "$prolog ERROR! The expected version string was not found in the docker image metadata."
-        return  $status
-    fi
-
-
-
-
-
 
     local deployment_context="opendap"
     if test "$DOCKER_NAME" = "ngap"; then deployment_context="ROOT"; fi
     loggy "$prolog     deployment_context: $deployment_context"
 
+    #################################################################################################
+    # Target specific tweaking using global values
+    # @TODO - refactor and move upstream where possible
+    local expected_version_str="$HYRAX_WEB_UI_VERSION"
+    if test "$DOCKER_NAME" = "besd"; then expected_version_str="$BES_VERSION"; fi
+    if test "$DOCKER_NAME" = "olfs"; then expected_version_str="$OLFS_VERSION"; fi
+    loggy "$prolog   expected_version_str: $expected_version_str"
+
+    local app_key="$DOCKER_NAME"
+    if test -n "$DOCKER_DIR"; then app_key="$DOCKER_DIR"; fi
+    if test "$app_key" = "ngap" ; then app_key="hyrax"; fi
+
+    local version_label_key="org.opendap.$app_key.version"
+    loggy "$prolog      version_label_key: $version_label_key"
+
+    #################################################################
+    # The check the docker image metadata (in .Config.Labels) for
+    # our version information.
+    test_docker_image_label "$d_id" "$version_label_key" "$expected_version_str"
+    status=$?
+    if test $status -ne 0; then
+        loggy "$prolog ERROR! The expected version string was not found in the docker image metadata."
+        return $status
+    fi
+
     #################################################################
     # The NGAP build has a static landing page that needs to match.
-    if test "$DOCKER_NAME" = "ngap"
-    then
-        test_file_in_image "$d_id" "/usr/share/tomcat/webapps/$deployment_context/docs/ngap/ngap.html" "$expected_version_str"
+    if test "$DOCKER_NAME" = "ngap"; then
+        test_file_in_docker_image "$d_id" "/usr/share/tomcat/webapps/$deployment_context/docs/ngap/ngap.html" "$expected_version_str"
         status=$?
-        if test $status -ne 0
-        then
+        if test $status -ne 0; then
             loggy "$prolog ERROR! The expected version string was not found in the file."
-            return  $status
+            return $status
         fi
     fi
 
@@ -185,18 +187,18 @@ function check_version() {
     # All the service deployments (except the besd) have the OLFS
     # installed in Tomcat. We check the version.xsl static file for
     # the Hyrax version.
-    if test "$DOCKER_NAME" != "besd"
-    then
+    if test "$DOCKER_NAME" != "besd"; then
         local version_xsl="/usr/share/tomcat/webapps/$deployment_context/xsl/version.xsl"
-        test_file_in_image "$d_id" "$version_xsl" "$HYRAX_WEB_UI_VERSION"
+        test_file_in_docker_image "$d_id" "$version_xsl" "$HYRAX_WEB_UI_VERSION"
         status=$?
-        if test $status -ne 0
-        then
+        if test $status -ne 0; then
             loggy "$prolog ERROR! The expected version string was not found in the file: '$d_id::$version_xsl'"
-            return  $status
+            return $status
         fi
     fi
     loggy "$prolog END"
     loggy "$HR1"
     return 0
 }
+
+check_version "$1"
